### ISSUE TITLE
Cannot connect to device

### ISSUE THREAD

**Issue by Apple2T4ch** [dwaan/homebridge-adb#1]
I just finished installing adb system wide on Windows 10 and can run adb version and it populates. I can also connect the device (Fire TV Edition) to adb and initiate commands. Homebridge is seeing the Fire TV but says it cant connect and therefore not showing up in Homekit. The popup even came up on the tv and I pressed accept.
![gdd](https://user-images.githubusercontent.com/52358231/89194540-20671700-d56d-11ea-9021-7994de93ff28.PNG)
![hff](https://user-images.githubusercontent.com/52358231/89194544-20671700-d56d-11ea-8a6a-67410b98fcc4.PNG)

 See attached photos. Thanks!

**Comment by dwaan** [comment]
Just making sure. If you type `adb devices` in your command prompt, does it show list of devices that are currently connected? 

What’s the result if you type this command: `adb -s your-ip-address shell “dumpsys power | grep mHoldingDisplay | cut -d = -f 2“`, that command will check if your device screen is on or off, so it should return true or false.

**Comment by Apple2T4ch** [comment]
Adb devices does show my device. I did also want to say that if I connect my device manually using cmd before starting homebridge that the plugin when booting seems to disconnect the adb device if that makes sense!
![shell](https://user-images.githubusercontent.com/52358231/89196554-fd8a3200-d56f-11ea-9e47-32b42cba3b8d.PNG)

**Comment by dwaan** [comment]
It seems that your ADB work properly. I think I knew the problem, I modified the script a little bit and update the plugins, please try and see the result.

**Comment by Apple2T4ch** [comment]
Working great now.  Thanks so much for this plugin!
