### ISSUE TITLE
Apple TV remote command

### ISSUE THREAD

**Issue by Alex565rf** [dwaan/homebridge-adb#10]
Hey !

Thank you so much for this plugin ! 

I would like to know if it's possible to change the "info" and "play/pause" in the apple tv remote app to use other commands like home, apps gallery etc.. Because i don't need the "info" and "play" button. 

And it is possible to add commands in inputs (not apps) ? 

Thank's a lot,

**Comment by dwaan** [comment]
Hey. Thanks for the input. Seems like a good idea.  I can open up the buttons and input to use other commands in the future. I will incorporate this in the future.

**Comment by Alex565rf** [comment]
Thank you, 
I have a quite bite delay before inputs go to the tv and some times the connexion is lost for few seconds. I have the android tv remote app on my smartphone who use the same protocol to send commands and it as very fast response time. Do u know if it is cause by my installation or the plugin is slow ?

**Comment by Alex565rf** [comment]
It seems possible to fully customize apple tv remote buttons, it could be so cool to personalized the inputs/Name & icons to match with android tv commands

![ios12-iphone-xs-home-control-center-apple-tv-remote](https://user-images.githubusercontent.com/71288814/93311480-58b57280-f806-11ea-9a20-17b4bbbe5b04.jpg)

**Comment by dwaan** [comment]
Hey, the delay caused by redundant connections. The way this plugin work is: it communicates to Homebridge, then the Homebridge communicate to android device using ADB command, so the lag is bound to happen. While your android remote control app probably communicate directly to your android device. 

If your device sometimes seems like it's not responding / lost connection in your Home app, try to lower the interval in config.json.

Sadly, Homebridge relies on the implementation of HAP protocol which is an open protocol that Apple released for noncomercial use. The HAP protocol have limitation and only support current remote interface. It also doesn't offer customization, so it can't support the remote interface like that Apple TV remote. So we're stuck with the d-pad, back, play-pause, and info button.

**Comment by Clickbaitcake** [comment]
It would be nice to have a HOME button as well. In some Android apps the back button isn't good enough to exit. Netflix for example requires you press the HOME button. I guess this button would just use ADB to open the home screen?

**Comment by Alex565rf** [comment]
Hey, Thank's for your help !

I find that on the HAP protocol it seems possible to had fasforward, next track etc. 
 
		case rewind = 0
		case fastforward = 1
		case nexttrack = 2
		case previoustrack = 3
		case arrowup = 4
		case arrowdown = 5
		case arrowleft = 6
		case arrowright = 7
		case select = 8
		case back = 9
		case exit = 10
		case playpause = 11
		case information = 15

**Comment by Clickbaitcake** [comment]
Nice thanks for the extra info. It would be nice to expose these to HomeBridge as controls/statuses so we could use Siri Shortcuts to pause/play etc

**Comment by Alex565rf** [comment]
The plugin work well when i click slowly on the apple tv remote, but when i spam a button ( for exemple:Down arrow when i want to quickly go to the end of a film/app list) it will have a lot of delay and will not work properly.

**Comment by Clickbaitcake** [comment]
> The plugin work well when i click slowly on the apple tv remote, but when i spam a button ( for exemple:Down arrow when i want to quickly go to the end of a film/app list) it will have a lot of delay and will not work properly.

This is probably more of an issue on your network @Alex565rf Is your Android device wireless? Could you change to wired?

**Comment by dwaan** [comment]
The current version implemented all of those variable, with it’s respected ADB command. But I myself still haven’t found how to access rewind, previoustrack and nexttrack via the control center remote. Anyway, I think the info button can be repurposed as home button in the future.

**Comment by dwaan** [comment]
> > The plugin work well when i click slowly on the apple tv remote, but when i spam a button ( for exemple:Down arrow when i want to quickly go to the end of a film/app list) it will have a lot of delay and will not work properly.
> 
> This is probably more of an issue on your network @Alex565rf Is your Android device wireless? Could you change to wired?

I experienced the delay myself like around half to a second lag. If I press down multiple time it delayed badly but it still do the rest of the command. I became more patient now and press the button slowly 😆😆. The functionality is as is for now, I think their’s nothing we can do to make it more responsive due to redundant connection.

**Comment by Alex565rf** [comment]
I'm wired on homebridge side but not on android tv side i will look a it. Ok cool for the info button it would be really nice. I like the @Clickbaitcake idea to add more commands who will show as a switch in homekit !

**Comment by Alex565rf** [comment]
> The current version implemented all of those variable, with it’s respected ADB command. But I myself still haven’t found how to access rewind, previoustrack and nexttrack via the control center remote. Anyway, I think the info button can be repurposed as home button in the future.

I will try to take a look at this

**Comment by dwaan** [comment]
Hey, I just updated the plugins for custom key event in Control Center Remote, check the readme for more information.

**Comment by Alex565rf** [comment]
Hey thanj you so much i will try this ! 
I juste have a problème, i change the homebridge port because i had pi hole on my rasbperry and now i see the Tv in homebridge but i can't add the tv in the home app ! 
I got this log: homebridge is running on port 51723.
[9/19/2020, 19:18:56] [HomebridgeADB] 192.168.0.50 - Connected
[9/19/2020, 19:18:56] [TuyaWebPlatform] Sending HTTP GET request to /homeassistant/skill - Header: {"name":"Discovery","namespace":"discovery","payloadVersion":1}.
[9/19/2020, 19:18:56] Projecteur BD49 is running on port 45671.
[9/19/2020, 19:18:56] Please add [Projecteur BD49] manually in Home app. Setup Code: 656-60-499

Did you have an ideo of how to change the port ? Thank you !

**Comment by dwaan** [comment]
As far as I know, homebridge accessories port is assigned automatically by homebridge. So it can’t be change manually. 

For your device that didn’t appear in home app. If it was in Home app before with the same name, then you might need to clear the homebridge accessories cache, just delete the accessory cache file in your persistent folder and restart homebridge. If you’re using Config UI X, there’s also an option to delete cached accessories in Homebridge Settings.

**Comment by Alex565rf** [comment]
Ok nice thank you. If someone else as the save probleme try the "reset homebridge accessories" option.
