### ISSUE TITLE
Alternate power on status check for poorly configured devices

### ISSUE THREAD

**Issue by scooterpsu** [dwaan/homebridge-adb#103]
**Is your feature request related to a problem? Please describe.**
Using 3 devices: Amazon FireStick, nVidia Shield Pro and a Dynalink Android TV box, 2/3 correctly report `mHoldingDisplaySuspendBlocker=false` when powered off. The Dynalink box somehow always reports `mHoldingDisplaySuspendBlocker=true`.

**Describe the solution you'd like**
Either switch to, or have an option to otherwise use `mWakefulness` to check on/off status.

`adb shell dumpsys power | grep mWakefulness` returns `mWakefulness=Awake` or `mWakefulness=Asleep` correctly on all 3 devices.

**Describe alternatives you've considered**
The homebridge Androidtv plugin seems pull the status from somewhere that reports correctly, but it's an otherwise inferior plugin.

**Additional context**
The way your plugin handles inputs is significantly better, so I'd love to use it exclusively.

**Comment by dwaan** [comment]
Thank you for the report, I’ll include this in the next update.

**Comment by scooterpsu** [comment]
This worked perfectly, thanks!
