### ISSUE TITLE
Show current hdmi in input

### ISSUE THREAD

**Issue by Faisalthe01** [dwaan/homebridge-adb#106]
Hi, is there any way to show current hdmi where the current app is displayed in the Home app?

**Comment by dwaan** [comment]
> Hi, is there any way to show current hdmi where the current app is displayed in the Home app?

Tbh, I don't have android based TV, so I can't suggest anything yet. 

However, if when you change your TV input to HDMI and it show the app id in homebridge logs, for example: com.android.tv.hdmi2 (not a real app id), you can use that as the app id in homebridge-adb config.
