### ISSUE TITLE
[Ideia] Sent hdmi-cec commands.

### ISSUE THREAD

**Issue by garlik82** [dwaan/homebridge-adb#12]
Hi. 
Started using this plugin yesterday, it works quite well.
I don’t know if this is possible but it would be nice to turn my tv on/off using my android tv box and this plugin.
Can adb sem hdmi-cec commands?

Thanks

**Comment by garlik82** [comment]
Just figured that some tomes my tv turns off other times and doesn’t. Sorry

**Comment by cardentey** [comment]
my LG OLED TV won't turn off  :-(
