### ISSUE TITLE
ADB with HOOBS

### ISSUE THREAD

**Issue by michaellongden** [dwaan/homebridge-adb#13]
Hi

I wonder if you can help me. I am using HOOBS and I have installed the Ad B plugin. I have input the below configuration but and HOOBS has accepted it but when I try and add the accessory via the Home App on iOS the Fire TV isn't showing under "Select an Accessory to Add to My Home" option. 

Is there something I am missing here? 

![Screenshot 2020-11-13 105417](https://user-images.githubusercontent.com/67514973/99064957-96ccd980-259e-11eb-83ff-b19a79fa22aa.png)

**Comment by dwaan** [comment]
Can you provide the log output?

**Comment by michaellongden** [comment]
3/11/2020, 10:23:28 Got SIGINT, shutting down Bridge...
13/11/2020, 10:23:33 Loaded plugin '@milo526/homebridge-tuya-web'
13/11/2020, 10:23:33 [11/13/2020, 3:23:33 AM] Registering platform 'milo526/homebridge-tuya-web.TuyaWebPlatform'
13/11/2020, 10:23:33 Loaded plugin 'homebridge-adb'
13/11/2020, 10:23:33 [11/13/2020, 3:23:33 AM] Registering platform 'homebridge-adb.HomebridgeADB'
13/11/2020, 10:23:34 Loaded plugin 'homebridge-ring'
13/11/2020, 10:23:34 [11/13/2020, 3:23:34 AM] Registering platform 'homebridge-ring.Ring'
13/11/2020, 10:23:34 Loaded plugin 'homebridge-samsung-tizen'
13/11/2020, 10:23:34 Loading 4 platforms...
13/11/2020, 10:23:34 [11/13/2020, 3:23:34 AM] Registering platform 'homebridge-samsung-tizen.SamsungTizen'
13/11/2020, 10:23:34 [TuyaWebPlatform] Initializing TuyaWebPlatform platform...
13/11/2020, 10:23:34 [Ring] Initializing Ring platform...
13/11/2020, 10:23:34 [SamsungTizen] Initializing SamsungTizen platform...
13/11/2020, 10:23:34 [HomebridgeADB] Initializing HomebridgeADB platform...
13/11/2020, 10:23:34 [TuyaWebPlatform] Loading accessory from cache: Tyler’s night light
13/11/2020, 10:23:34 [TuyaWebPlatform] Loading accessory from cache: Girls TV
13/11/2020, 10:23:34 [TuyaWebPlatform] Loading accessory from cache: Mirror
13/11/2020, 10:23:34 [TuyaWebPlatform] Loading accessory from cache: Tyler’s Bedroom Light
13/11/2020, 10:23:34 [TuyaWebPlatform] Loading accessory from cache: Girl’s Bedroom Light
13/11/2020, 10:23:34 [TuyaWebPlatform] Loading accessory from cache: Tyler’s TV
13/11/2020, 10:23:34 [TuyaWebPlatform] Loading accessory from cache: Kitchen TV
13/11/2020, 10:23:34 [TuyaWebPlatform] Loading accessory from cache: Bedroom Bulb
13/11/2020, 10:23:34 [TuyaWebPlatform] Loading accessory from cache: Lamp
13/11/2020, 10:23:34 [TuyaWebPlatform] Loading accessory from cache: Girl’s night light
13/11/2020, 10:23:34 [Ring] Configuring cached accessory 9eae8153-795b-4b76-8541-71e16be9fa05 Front Door
13/11/2020, 10:23:34 [Ring] Configuring cached accessory c4e5d31f-f04e-445a-b267-b9013d6c50f7 Downstairs
13/11/2020, 10:23:34 [HomebridgeADB] -------------------------------------------------
13/11/2020, 10:23:34 [HomebridgeADB] Please add one or more accessories in your config
13/11/2020, 10:23:34 [HomebridgeADB] -------------------------------------------------
13/11/2020, 10:23:37 Bridge is running on port 51826.
13/11/2020, 10:23:37 External port pool ran out of ports. Fallback to random assign.
13/11/2020, 10:23:37 [TV] Samsung 7 Series is running on port 43247.
13/11/2020, 10:23:37 Please add [[TV] Samsung 7 Series] manually in Home app. Setup Code: 031-45-154

**Comment by michaellongden** [comment]
Oh one sec... this could be the issue:
13/11/2020, 11:37:43 [HomebridgeADB] 

Can't connect to "Girl's Fire TV",
with IP address: 192.168.1.244.
Please check you ADB connection,
or make sure your device is on
and connected to the same network

**Comment by dwaan** [comment]
Hey. Make sure ADB is up and running in your Hoobs server. You can follow the steps in README.md on how to install ADB in your server.

**Comment by michaellongden** [comment]
Is a Fire TV stick something that should be supported using this plugin? I am getting the following error:
hoobs@hoobs:/home/hoobs/.hoobs/etc $ adb tcpip 5555
* daemon not running; starting now at tcp:5037
* daemon started successfully
error: device unauthorized.
This adb server's $ADB_VENDOR_KEYS is not set
Try 'adb kill-server' if that seems wrong.
Otherwise check for a confirmation dialog on your device.

**Comment by dwaan** [comment]
This plugins work as an interface for ADB to control any Android device regardless the brand, as ADB should work on any Android devices. The only requirement is that ADB command can connect to the device using WiFI.

The "error: device unauthorized ..." means that you haven't approve the ADB connection in your android device, your device should display a confirmation dialog requestion for your permission. If not, your need to kill the ADB and restart the ADB connection, as the output suggested.

**Comment by michaellongden** [comment]
Hey, thanks for your help. I got there in the end. All working great now.

**Comment by michaellongden** [comment]
Spoke too soon... Do you know why I would be seeing this:
16/11/2020, 15:50:14 [HomebridgeADB] Creating: Girl's Fire TV
16/11/2020, 15:50:14 Bridge is running on port 51826.
16/11/2020, 15:50:14 [HomebridgeADB] 192.168.1.244 - Connected
16/11/2020, 15:50:14 External port pool ran out of ports. Fallback to random assign.
16/11/2020, 15:50:14 [TV] Samsung 7 Series is running on port 40723.
16/11/2020, 15:50:14 Please add [[TV] Samsung 7 Series] manually in Home app. Setup Code: 031-45-154
16/11/2020, 15:50:14 [HomebridgeADB] --------------------------------------------------------------
16/11/2020, 15:50:14 [HomebridgeADB] 192.168.1.244 - Can't get information from Girl's Fire TV
16/11/2020, 15:50:14 [HomebridgeADB] 192.168.1.244 - Please check you ADB connection
16/11/2020, 15:50:14 [HomebridgeADB] --------------------------------------------------------------

It is saying it is connected and then straight away saying the 192.168.1.244 - Please check you ADB connection
