### ISSUE TITLE
Allow defining Home app id

### ISSUE THREAD

**Issue by fearlesschicken** [dwaan/homebridge-adb#16]
Hi there, 
I was wondering if there was a way to define the home app.  In my use case, my firetv's "Home" is com.amazon.tv.launcher and using the 1st input of "Home" does go to this correctly.  However, it detects the app and creates an additional input in the list.

**Comment by dwaan** [comment]
Hey, the "Home" input was created to detect the system launcher automatically without any configuration, and there is also "Other" input which also created automatically for previous launched app. However if you add additional inputs in the config with the com.amazon.tv.launcher id, then it should appear twice - Home and the input that you create. If this the case, I suggest you to just remove your costum input and use the default "Home" instead. But in the case you wanted to hide the default "Home" input, or replace it with your own id, I can update the plugins in the future.
