### ISSUE TITLE
ADB reconnect at interval

### ISSUE THREAD

**Issue by Clickbaitcake** [dwaan/homebridge-adb#17]
I am running this wonderful integration to control my Nvidia Shield. The issue is, if the Shield restarts the ADB control no longer works until I run the `abd connect 191.168.2` command from the terminal on my Homebridge.

I think this is a security feature of the Shield. 

Could functionality be added that checks for connectivity to the target android device by running `adb devices` and then runing the `adb connect` command if its not in the list? 

`adb devices` gives the following info:

```
pi@homebridge:/var/lib/homebridge $ adb devices
List of devices attached
192.168.0.2:5555       device
```

**Comment by dwaan** [comment]
The script actually have “adb connect” in the beginning of each connection. As, I tested this script with my Nvidia shield also. Still trying to figure out what’s the best way to avoid this connection problem.

**Comment by Clickbaitcake** [comment]
Okay thanks, it seems like the issue happens when the Shield is turned off, it looses connection.
I think we could check the list of devices and run connect command if not connected `adb devices` is the command for this. 

Can the Pi run `adb devices` at intervals and then run a `adb connect` if there are no attached devices?

**Comment by dwaan** [comment]
Please check the new version. The plugins now will try to  do `adb connect` when home app request it's status, so hopefully it will fix this kind of problem.
