### ISSUE TITLE
Hoobs not work

### ISSUE THREAD

**Issue by equal151** [dwaan/homebridge-adb#18]
Hello sorry for my bad englisch.
I have a problem i installed adb on my hoobs server and i avtivadted adb debuggin on my firetv stick.
Than i use the Terminal i can run command on de stick but in de log of hoobs cant connect to adb
`7.12.2020, 20:23:47 [HomebridgeADB] 192.168.2.7 - Connected`
`7.12.2020, 20:23:47 [HomebridgeADB] --------------------------------------------------------------`
`7.12.2020, 20:23:47 [HomebridgeADB] 192.168.2.7 - Can't get information from FireTV-Schlafzimmer`
`7.12.2020, 20:23:47 [HomebridgeADB] 192.168.2.7 - Please check you ADB connection`
`7.12.2020, 20:23:47 [HomebridgeADB] --------------------------------------------------------------`

`hoobs@hoobs:/home/hoobs/.hoobs/etc $ adb version`
`Android Debug Bridge version 1.0.39`
`Version 1:8.1.0+r23-5`
`Installed as /usr/lib/android-sdk/platform-tools/adb`

`hoobs@hoobs:/home/hoobs/.hoobs/etc $ adb devices`
`List of devices attached`
`192.168.2.7:5555        device`

If i ran this command i become an error
`hoobs@hoobs:~ $ adb shell 'dumpsys power | grep mHoldingDisplay | cut -d = -f 2'`
`/system/bin/sh: cut: not found`

**Comment by dwaan** [comment]
Hey Thank you for the information. I believe the problem is inside your Android device, it doesn’t have “cut” command used to trim string. I assumed the “cut” command should be available inside every android, will going to figure out other way to overcome this.

**Comment by dwaan** [comment]
Please check the new version. I remove the `cut` command, but don't have firestick to test if the newer version works or not.

**Comment by equal151** [comment]
Hank you ist Works good👍🏻
