### ISSUE TITLE
[Question] Turn on/off the TV

### ISSUE THREAD

**Issue by facutopa** [dwaan/homebridge-adb#2]
Hi @dwaan 

First of all, thanks for this plugin! I had been using the broadlink plugin, but I was sure that a plugin for Android TV was possible regardless of the brand of the TV.

One question, I saw is possible to turn off the TV, but is possible to turn on?

**Comment by dwaan** [comment]
Hey, it's a bit unclear what your question is. But I assumed that you have a TV with Android TV. If yes, this plugins only do Sleep and Wake Up, like when you press power button on your Android device, it only turning on / off the screen, it's not really turning off or on the device as it need active network connection to make the plugins work. 

My own setup is an Android TV box connected to TV, and I just activate the HDMI CEC in both devices to sync the power status.

**Comment by facutopa** [comment]
Yes, you're correct with your suposition. I have a TV with android tv.
Thanks for your answer and help!
