### ISSUE TITLE
/system/bin/sh: cut: not found

### ISSUE THREAD

**Issue by mfilej** [dwaan/homebridge-adb#22]
I'm having an issue running the example code from the README:

```
$ adb -s 192.168.8.203 shell 'dumpsys power | grep mHoldingDisplay | cut -d = -f 2'                                         ↪ 1

/system/bin/sh: cut: not found
```

Sounds like the `cut` command is not available on my tv box. Not sure if there is anything I can do on the box?

**Comment by dwaan** [comment]
Which version that you use? The latest version remove all the cut commands inside the plugins. You can update the latest version of you haven’t.

**Comment by mfilej** [comment]
Understood. My issue was only running the snippets from the README. I've issued a PR to change the README in case you're interested.
