### ISSUE TITLE
"Can't get information from TV box"

### ISSUE THREAD

**Issue by mfilej** [dwaan/homebridge-adb#24]
When I restart Homebridge I see this in the output:
<img width="1133" alt="Screenshot 2020-12-30 at 22 04 53" src="https://user-images.githubusercontent.com/3621/103381082-0cf3b400-4aeb-11eb-943a-199deaceb0ae.png">

But if I run the mentioned command myself it seems to work fine:
```
$ adb -s 192.168.8.203 shell "getprop ro.product.model && getprop ro.product.manufacturer && getprop ro.serialno"
KSTB6020
KaonMedia
BS10059827013960
```

I also tried running the commands as the `homebridge` user.

**Comment by dwaan** [comment]
Is this happens all the time? Does the plugins work even with that warning?

**Comment by mfilej** [comment]
No, it did not happen all the time and yes, the plugin still worked after the warning.

However I don't have that TV box anymore so I can't give you any more info unfortunately.
