### ISSUE TITLE
Not possible to install ADB

### ISSUE THREAD

**Issue by abubakaraz** [dwaan/homebridge-adb#25]
Hi, i try to install ADB on my Docker Homebridge but this is the error that i receive:

 
ERROR: unsatisfiable constraints:
  so:libprotobuf.so.24 (missing):
    required by: android-tools-30.0.5-r0[so:libprotobuf.so.24]

<img width="1096" alt="Bildschirmfoto 2021-01-03 um 22 49 19" src="https://user-images.githubusercontent.com/44671143/103489588-f369a980-4e15-11eb-967b-3d3c2a6cc491.png">

**Comment by fire1ce** [comment]
+1

**Comment by andre-sasaki** [comment]
Same problem here

**Comment by dotWee** [comment]
Looks like the package on the testing repository causes this issue. Adding fall-back repositories seem to fix this.

Use this command to install the android-tools on Alpine Linux:

```bash
docker exec homebridge apk add android-tools --update-cache \
        --repository https://alpine.global.ssl.fastly.net/alpine/edge/community \
        --repository https://alpine.global.ssl.fastly.net/alpine/edge/main \
        --repository https://dl-3.alpinelinux.org/alpine/edge/testing \
        --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing
```

**Comment by Tech-S1** [comment]
<img width="421" alt="Screenshot 2021-01-17 at 20 18 44" src="https://user-images.githubusercontent.com/74782108/104854914-4efd6200-5901-11eb-8760-2d18ecb49c14.png">
Installed like above but when trying to connect it does not seem to error, it just does nothing. Then no devices show as connected in adb. Tried pinging the IP and seems to get a response, and ADB Debugging is turned on.

**Comment by dotWee** [comment]
Maybe try reseting the ADB connection key (delete file `/homebridge/.android/adbkey` & `/homebridge/.android/adbkey`).

**Comment by abubakaraz** [comment]
Same issue 
Tried to delte the Adbkey files but no different

**Comment by dwaan** [comment]
@Tech-S1 @abubakaraz So you able to install ADB now, but still can't connect to your Android device? Does this help your issue? I assumed your homebridge server and your Android Device are communicating via WiFi, right now.

> Some Android device doesn't have remote debug by default. If your device is one of them, connect your device with USB cable to your server (or any computer with ADB installed) and run this command:
> 
> `adb tcpip 5555`
> 
> after that, just disconnect the USB cable from your server.

**Comment by Tech-S1** [comment]
I was using the Alpine image for ozun/homebridge. I did the same but with the Ubuntu version of the image and it worked for me. I can only thing the Alpine version was missing some libraries it needed.

**Comment by dwaan** [comment]
> I was using the Alpine image for ozun/homebridge. I did the same but with the Ubuntu version of the image and it worked for me. I can only think the Alpine version was missing some libraries it needed.

That's great. So you now able to connect to your Android device with the ADB command?

**Comment by dotWee** [comment]
> Same issue
> Tried to delte the Adbkey files but no different

Are you using the homebridge docker image for ARM (like Raspberry Pi)? It looks like the binaries on the official Alpine Repository for ARMv6/v7 are broken and having issues resolving package dependencies. Switching to the Debian/Ubuntu docker image like @Tech-S1 did fixed it for me.

**Comment by Goldsucher** [comment]
is there already a solution for the alpine docker? Still can't install adb:

`/homebridge # apk --update-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing/ add android-tools
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  android-tools (no such package):
    required by: world[android-tools]`

**Comment by dotWee** [comment]
Tried lots of different approaches but just couldn't get it to work. If you ask me, something is fucked up with Alpine's adb binaries.

**Comment by Goldsucher** [comment]
ehhm I tried your idea from above and that worked for me. I pasted it into the homebridge ui terminal (without docker exec of course like that):

`apk add android-tools --update-cache \
        --repository https://alpine.global.ssl.fastly.net/alpine/edge/community \
        --repository https://alpine.global.ssl.fastly.net/alpine/edge/main \
        --repository https://dl-3.alpinelinux.org/alpine/edge/testing \
        --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing`

**Comment by dotWee** [comment]
> ehhm I tried your idea from above and that worked for me. I pasted it into the homebridge ui terminal (without docker exec of course like that):
> 
> 
> 
> `apk add android-tools --update-cache \
> 
>         --repository https://alpine.global.ssl.fastly.net/alpine/edge/community \
> 
>         --repository https://alpine.global.ssl.fastly.net/alpine/edge/main \
> 
>         --repository https://dl-3.alpinelinux.org/alpine/edge/testing \
> 
>         --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing`
> 
> 
> 
> 

Ah yes, _that guy_. Wouldn't trust him. He fucked up all my clusters. 😉




Seriously tho, I'm currently looking into what actually went wrong with the official ADB binaries in the Alpine repo. Using another 3rd party repo shouldn't be a solution.

**Comment by Goldsucher** [comment]
New Problem since last update of homebridge/plugin:

So far it worked when I run this command:

`apk add android-tools --update-cache \
        --repository https://alpine.global.ssl.fastly.net/alpine/edge/community \
        --repository https://alpine.global.ssl.fastly.net/alpine/edge/main \
        --repository https://dl-3.alpinelinux.org/alpine/edge/testing \
        --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing`

but now every adb command results in the same error:

`Error relocating /usr/bin/adb: _ZSt28__throw_bad_array_new_lengthv: symbol not found
Error relocating /usr/bin/adb: _ZNKRSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEE3strEv: symbol not found`

does anybody know how to solve this?

**Comment by dwaan** [comment]
> New Problem since last update of homebridge/plugin:
> 
> So far it worked when I run this command:
> 
> `apk add android-tools --update-cache \ --repository https://alpine.global.ssl.fastly.net/alpine/edge/community \ --repository https://alpine.global.ssl.fastly.net/alpine/edge/main \ --repository https://dl-3.alpinelinux.org/alpine/edge/testing \ --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing`
> 
> but now every adb command results in the same error:
> 
> `Error relocating /usr/bin/adb: _ZSt28__throw_bad_array_new_lengthv: symbol not found Error relocating /usr/bin/adb: _ZNKRSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEE3strEv: symbol not found`
> 
> does anybody know how to solve this?

This is the problem with alpine edge repository, the adb binary is broken. In the newer README I updated the how to repo into using v3.14. It’s what I’m currently using right now. 

`apk --update-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.14/community/ add android-tools`

For the original problem, I finally figure out the problem. Just use this command to install libprotobuf:

`apk add libprotobuf`

**Comment by Goldsucher** [comment]
ok thanks for your help. Tried a bit but it doesn't work yet. 

`apk add libprotobuf`

seems to work:

`
/homebridge # apk add libprotobuf
OK: 428 MiB in 146 packages
`

but if I try 

`apk --update-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.14/community/ add android-tools`

I'm getting the error:

`
/homebridge # apk --update-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.14/community/ add android-tools
fetch http://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  so:libprotobuf.so.26 (no such package):
    required by: android-tools-31.0.0p1-r2[so:libprotobuf.so.26]`

**Comment by dwaan** [comment]
> ok thanks for your help. Tried a bit but it doesn't work yet.
> 
> `apk add libprotobuf`
> 
> seems to work:
> 
> `/homebridge # apk add libprotobuf OK: 428 MiB in 146 packages`
> 
> but if I try
> 
> `apk --update-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.14/community/ add android-tools`
> 
> I'm getting the error:
> 
> ` /homebridge # apk --update-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.14/community/ add android-tools fetch http://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz ERROR: unable to select packages: so:libprotobuf.so.26 (no such package): required by: android-tools-31.0.0p1-r2[so:libprotobuf.so.26]`
> 
> EDIT: Okay I don't really know how, but now it works. Maybe
> 
> `apk del protobuf`
> 
> did the trick but that makes no sense. Anyway, thanks!

Ouch, that's strange. But if it's working then it's working. :D

**Comment by Goldsucher** [comment]
okay since the last update of the docker image, the error is back.

I'll try to solve the problem again and post an update

**Comment by owine** [comment]
> okay since the last update of the docker image, the error is back.
> 
> I'll try to solve the problem again and post an update
> 
> EDIT: Solved it. I added
> 
> `http://dl-cdn.alpinelinux.org/alpine/v3.14/main/` `http://dl-cdn.alpinelinux.org/alpine/v3.14/community/`
> 
> to
> 
> `/etc/apk/repositories`
> 
> than
> 
> `apk add android-tools`
> 
> worked straight.
> 
> to prevent the error in the next update, maybe this startscript could help (untested):
> 
> sudo echo 'http://dl-cdn.alpinelinux.org/alpine/v3.14/main/' >> /etc/apk/repositories sudo echo '[http://dl-cdn.alpinelinux.org/alpine/v3.14/community/‚](http://dl-cdn.alpinelinux.org/alpine/v3.14/community/%E2%80%9A) >> /etc/apk/repositories apk add android-tools

This worked for me, however there is a typo in your second command. The following corrects the typo:

```
sudo echo 'http://dl-cdn.alpinelinux.org/alpine/v3.14/main/' >> /etc/apk/repositories
sudo echo 'http://dl-cdn.alpinelinux.org/alpine/v3.14/community/' >> /etc/apk/repositories
apk add android-tools
```

**Comment by dwaan** [comment]
Regarding the adb installation especially inside the Homebridge docker image tips and trick from this thread were summarized in the latest README.md
