### ISSUE TITLE
More granularity in selecting media...

### ISSUE THREAD

**Issue by Geefer1985** [dwaan/homebridge-adb#27]
Hello! Love the plugin! I have found you can use ADB commands such as:

adb shell am start -c android.intent.category.LEANBACK_LAUNCHER -a android.intent.action.VIEW -d http://www.netflix.com/watch/70202141 -f 0x10808000 -e source 30 com.netflix.ninja/.MainActivity

To bring the (in my case) Fire Stick TV to a specific show in Netflix. 

Am I able to do this currently? Or is this something that needs to be done a different way?

**Comment by dwaan** [comment]
Hey, the new version added option to run ADB shell command.
