### ISSUE TITLE
Connection issues using Fire TV

### ISSUE THREAD

**Issue by snarknesor** [dwaan/homebridge-adb#29]
I am using this with an Insignia Fire TV and when it works, it works great. But sometimes it will randomly disconnect  and show 'no response' in HomeKit. The logs show:

1/26/2021, 9:08:52 AM [HomebridgeADB] my-ip - Reconnecting
1/26/2021, 9:08:52 AM [HomebridgeADB] 

Problem when getting device power status.
1/26/2021, 9:08:52 AM [HomebridgeADB] If your network works fine, please report this output.
1/26/2021, 9:08:52 AM [HomebridgeADB] 1. When running this command
1/26/2021, 9:08:52 AM [HomebridgeADB] adb -s  my-ip shell "dumpsys power | grep mHoldingDisplay"
1/26/2021, 9:08:52 AM [HomebridgeADB] 2. Output:
1/26/2021, 9:08:52 AM [HomebridgeADB] 
1/26/2021, 9:08:52 AM [HomebridgeADB] 3. Error output:
1/26/2021, 9:08:52 AM [HomebridgeADB] error: device my-ip not found

when I kill the server and reconnect it looks fine but then I ask for the status of the device and it says it cannot be found:
hoobs@hoobs:/home/hoobs/.hoobs/etc $ adb kill-server
hoobs@hoobs:/home/hoobs/.hoobs/etc $ adb connect my_ip
* daemon not running; starting now at tcp:5037
* daemon started successfully
connected to my-IP
hoobs@hoobs:/home/hoobs/.hoobs/etc $ adb -s my-ip  shell 'dumpsys power | grep mHoldingDisplay | cut -d = -f 2'
error: device 'my-ip' not found

Again, sometimes this happens and sometimes it doesnt have connection issues and works fine

**Comment by dwaan** [comment]
Does it happened when your Fire TV turned off?

**Comment by snarknesor** [comment]
It’s not happening consistently. Sometimes it  connects when the tv is off and sometimes it doesn’t

**Comment by dwaan** [comment]
My guess is your TV disconnected from your network when it turned off. 

Try running `adb -s my-ip shell "dumpsys power | grep mHoldingDisplay"` few times, few minutes after your TV turned off, and let me know the result. If it return one single error, then it confirm that your TV sometimes disconnected from your network when it turned off. If this is the case, then there's nothing I can do. 

But on the side note, I think some TV have an option to always keep network connection alive.

**Comment by pawelosin** [comment]
The same issue. In my case when i turned the tv off via homekit app after few seconds the app shows that tv is on even though it is off. Then i have to turn the tv on next use commands adb kill-server and adb connect my_ip and next restart homebridge. After that, I have access to the TV from the Homekit app.

**Comment by dwaan** [comment]
> The same issue. In my case when i turned the tv off via homekit app after few seconds the app shows that tv is on even though it is off. Then i have to turn the tv on next use commands adb kill-server and adb connect my_ip and next restart homebridge. After that, I have access to the TV from the Homekit app.

Do you mind to debug it for me? As I need to understand the technical problem. 

First, turn off your TV with remote wait for few minutes then from your computer run: ‘adb -s your-tv-ip shell "dumpsys power | grep mHoldingDisplay"’, check your Home app whether your TV is off or not. 

Next, turn off your TV using home app, wait for few minutes, and then run the same command. 

The expected result of that command should contain ‘false’. But let me know any output of that command.

**Comment by pawelosin** [comment]
When the device is off I run adb -s your-tv-ip shell "dumpsys power | grep mHoldingDisplay" the result is empty line.

It is my log file. The name of my device is KII.

^[[37m[17.03.2021, 07:32:23] ^[[39m^[[36m[HomebridgeADB]^[[39m KII - Sleeping
^[[37m[17.03.2021, 07:32:29] ^[[39m^[[36m[RTV]^[[39m Received MQTT: tele/Sonoffpow/SENSOR = {"Time":"2021-03-17T07:32:29","ENERGY":{"TotalStartTime":"2019-12-23T13:15:19","Total"$
^[[37m[17.03.2021, 07:32:29] ^[[39m^[[36m[RTV]^[[39m ^[[90m**Fakegato-timer: addData  RTV { time: 1615962749, power: 0 }  immediate:  false^[[39m
^[[37m[17.03.2021, 07:32:44] ^[[39m^[[36m[RTV]^[[39m Received MQTT: tele/Sonoffpow/SENSOR = {"Time":"2021-03-17T07:32:44","ENERGY":{"TotalStartTime":"2019-12-23T13:15:19","Total"$
^[[37m[17.03.2021, 07:32:44] ^[[39m^[[36m[RTV]^[[39m ^[[90m**Fakegato-timer: addData  RTV { time: 1615962764, power: 0 }  immediate:  false^[[39m
^[[37m[17.03.2021, 07:32:47] ^[[39m^[[36m[Philips TV]^[[39m ^[[90mEntering getPowerState with context: statuspoll and current value: false^[[39m
^[[37m[17.03.2021, 07:32:47] ^[[39m^[[36m[Philips TV]^[[39m ^[[90mEntering getMutedState with context: statuspoll and current state: false^[[39m
^[[37m[17.03.2021, 07:32:47] ^[[39m^[[36m[Philips TV]^[[39m ^[[90mEntering getVolumeLevel with context: statuspoll and current value: 0^[[39m
^[[37m[17.03.2021, 07:32:49] ^[[39m^[[36m[Philips TV]^[[39m ^[[90mgetPowerState - ERROR: ETIMEDOUT^[[39m
^[[37m[17.03.2021, 07:32:59] ^[[39m^[[36m[RTV]^[[39m Received MQTT: tele/Sonoffpow/SENSOR = {"Time":"2021-03-17T07:32:59","ENERGY":{"TotalStartTime":"2019-12-23T13:15:19","Total"$
^[[37m[17.03.2021, 07:32:59] ^[[39m^[[36m[RTV]^[[39m ^[[90m**Fakegato-timer: addData  RTV { time: 1615962779, power: 0 }  immediate:  false^[[39m
^[[37m[17.03.2021, 07:33:02] ^[[39m^[[36m[Philips TV]^[[39m ^[[90mEntering getPowerState with context: undefined and current value: false^[[39m
^[[37m[17.03.2021, 07:33:13] ^[[39m^[[36m[Philips TV]^[[39m ^[[90mEntering getPowerState with context: undefined and current value: false^[[39m
^[[37m[17.03.2021, 07:33:14] ^[[39m^[[36m[RTV]^[[39m Received MQTT: tele/Sonoffpow/SENSOR = {"Time":"2021-03-17T07:33:14","ENERGY":{"TotalStartTime":"2019-12-23T13:15:19","Total"$
^[[37m[17.03.2021, 07:33:14] ^[[39m^[[36m[RTV]^[[39m ^[[90m**Fakegato-timer: addData  RTV { time: 1615962794, power: 0 }  immediate:  false^[[39m
^[[37m[17.03.2021, 07:33:21] ^[[39m^[[36m[Philips TV]^[[39m ^[[90mEntering getPowerState with context: undefined and current value: false^[[39m
^[[37m[17.03.2021, 07:33:29] ^[[39m^[[36m[RTV]^[[39m Received MQTT: tele/Sonoffpow/SENSOR = {"Time":"2021-03-17T07:33:29","ENERGY":{"TotalStartTime":"2019-12-23T13:15:19","Total"$
^[[37m[17.03.2021, 07:33:29] ^[[39m^[[36m[RTV]^[[39m ^[[90m**Fakegato-timer: addData  RTV { time: 1615962809, power: 0 }  immediate:  false^[[39m
^[[37m[17.03.2021, 07:33:44] ^[[39m^[[36m[RTV]^[[39m Received MQTT: tele/Sonoffpow/SENSOR = {"Time":"2021-03-17T07:33:44","ENERGY":{"TotalStartTime":"2019-12-23T13:15:19","Total"$
^[[37m[17.03.2021, 07:33:44] ^[[39m^[[36m[RTV]^[[39m ^[[90m**Fakegato-timer: addData  RTV { time: 1615962824, power: 0 }  immediate:  false^[[39m
^[[37m[17.03.2021, 07:33:47] ^[[39m^[[36m[Philips TV]^[[39m ^[[90mEntering getPowerState with context: statuspoll and current value: false^[[39m
^[[37m[17.03.2021, 07:33:47] ^[[39m^[[36m[Philips TV]^[[39m ^[[90mEntering getMutedState with context: statuspoll and current state: false^[[39m
^[[37m[17.03.2021, 07:33:47] ^[[39m^[[36m[Philips TV]^[[39m ^[[90mEntering getVolumeLevel with context: statuspoll and current value: 0^[[39m
^[[37m[17.03.2021, 07:33:49] ^[[39m^[[36m[Philips TV]^[[39m ^[[90mEntering getPowerState with context: undefined and current value: false^[[39m
^[[37m[17.03.2021, 07:33:49] ^[[39m^[[36m[Philips TV]^[[39m ^[[90mgetPowerState - ERROR: ETIMEDOUT^[[39m
^[[37m[17.03.2021, 07:33:58] ^[[39m^[[36m[MiAqaraPlatform]^[[39m ^[[90m[DEBUG][Revc]{"cmd":"report","model":"sensor_motion.aq2","sid":"158d0002b486ba","short_id":48434,"data":"{\$
^[[37m[17.03.2021, 07:33:58] ^[[39m^[[36m[RTV]^[[39m ^[[90m**Fakegato-timer: addData  Przedpokój Czujnik Ruchu { time: 1615962838, status: 0 }  immediate:  true^[[39m
^[[37m[17.03.2021, 07:33:58] ^[[39m^[[36m[RTV]^[[39m ^[[90m**Fakegato-timer: executeImmediateCallback**^[[39m
^[[37m[17.03.2021, 07:33:58] ^[[39m^[[36m[MiAqaraPlatform]^[[39m ^[[90m**Fakegato-timer callbackMotion:  Przedpokój Czujnik Ruchu , immediate:  true , entry:  { time: 1615962838,$
^[[37m[17.03.2021, 07:33:58] ^[[39m^[[36m[MiAqaraPlatform]^[[39m ^[[90mFirst entry Przedpokój Czujnik Ruchu: 0^[[39m
^[[37m[17.03.2021, 07:33:58] ^[[39m^[[36m[MiAqaraPlatform]^[[39m ^[[90mLast entry Przedpokój Czujnik Ruchu: c56^[[39m
^[[37m[17.03.2021, 07:33:58] ^[[39m^[[36m[MiAqaraPlatform]^[[39m ^[[90mUsed memory Przedpokój Czujnik Ruchu: c56^[[39m
^[[37m[17.03.2021, 07:33:58] ^[[39m^[[36m[RTV]^[[39m ^[[90m**Fakegato-timer: addData  Przedpokój Czujnik Ruchu { time: 1615962838, status: 0 }  immediate:  true^[[39m
^[[37m[17.03.2021, 07:33:58] ^[[39m^[[36m[RTV]^[[39m ^[[90m**Fakegato-timer: executeImmediateCallback**^[[39m
^[[37m[17.03.2021, 07:33:58] ^[[39m^[[36m[MiAqaraPlatform]^[[39m ^[[90m**Fakegato-timer callbackMotion:  Przedpokój Czujnik Ruchu , immediate:  true , entry:  { time: 1615962838,$
^[[37m[17.03.2021, 07:33:58] ^[[39m^[[36m[MiAqaraPlatform]^[[39m ^[[90mFirst entry Przedpokój Czujnik Ruchu: 0^[[39m
^[[37m[17.03.2021, 07:33:58] ^[[39m^[[36m[MiAqaraPlatform]^[[39m ^[[90mLast entry Przedpokój Czujnik Ruchu: c56^[[39m
^[[37m[17.03.2021, 07:33:58] ^[[39m^[[36m[MiAqaraPlatform]^[[39m ^[[90mUsed memory Przedpokój Czujnik Ruchu: c56^[[39m
^[[37m[17.03.2021, 07:33:58] ^[[39m^[[36m[MiAqaraPlatform]^[[39m ^[[90m116 Przedpokój Czujnik Ruchu: e3be050000000000731bfc2502 1301 1c01570cc00f00000000000000000101^[[39m
^[[37m[17.03.2021, 07:33:59] ^[[39m^[[36m[RTV]^[[39m ^[[90m** Fakegato-storage write FS file: /var/lib/homebridge/accessories/raspberrypi_Przedpokój Czujnik Ruchu_persist.json "f$
^[[37m[17.03.2021, 07:33:59] ^[[39m^[[36m[RTV]^[[39m Received MQTT: tele/Sonoffpow/SENSOR = {"Time":"2021-03-17T07:33:59","ENERGY":{"TotalStartTime":"2019-12-23T13:15:19","Total"$
^[[37m[17.03.2021, 07:33:59] ^[[39m^[[36m[RTV]^[[39m ^[[90m**Fakegato-timer: addData  RTV { time: 1615962839, power: 0 }  immediate:  false^[[39m
^[[37m[17.03.2021, 07:34:14] ^[[39m^[[36m[RTV]^[[39m Received MQTT: tele/Sonoffpow/SENSOR = {"Time":"2021-03-17T07:34:14","ENERGY":{"TotalStartTime":"2019-12-23T13:15:19","Total"$
^[[37m[17.03.2021, 07:34:14] ^[[39m^[[36m[RTV]^[[39m ^[[90m**Fakegato-timer: addData  RTV { time: 1615962854, power: 0 }  immediate:  false^[[39m
^[[37m[17.03.2021, 07:34:29] ^[[39m^[[36m[RTV]^[[39m Received MQTT: tele/Sonoffpow/SENSOR = {"Time":"2021-03-17T07:34:29","ENERGY":{"TotalStartTime":"2019-12-23T13:15:19","Total"$
^[[37m[17.03.2021, 07:34:29] ^[[39m^[[36m[RTV]^[[39m ^[[90m**Fakegato-timer: addData  RTV { time: 1615962869, power: 0 }  immediate:  false^[[39m
^[[37m[17.03.2021, 07:34:44] ^[[39m^[[36m[RTV]^[[39m Received MQTT: tele/Sonoffpow/SENSOR = {"Time":"2021-03-17T07:34:44","ENERGY":{"TotalStartTime":"2019-12-23T13:15:19","Total"$
^[[37m[17.03.2021, 07:34:44] ^[[39m^[[36m[RTV]^[[39m ^[[90m**Fakegato-timer: addData  RTV { time: 1615962884, power: 0 }  immediate:  false^[[39m
^[[37m[17.03.2021, 07:34:47] ^[[39m^[[36m[Philips TV]^[[39m ^[[90mEntering getPowerState with context: statuspoll and current value: false^[[39m
^[[37m[17.03.2021, 07:34:47] ^[[39m^[[36m[Philips TV]^[[39m ^[[90mEntering getMutedState with context: statuspoll and current state: false^[[39m
^[[37m[17.03.2021, 07:34:47] ^[[39m^[[36m[Philips TV]^[[39m ^[[90mEntering getVolumeLevel with context: statuspoll and current value: 0^[[39m
^[[37m[17.03.2021, 07:34:49] ^[[39m^[[36m[Philips TV]^[[39m ^[[90mgetPowerState - ERROR: ETIMEDOUT^[[39m
[xmldom error]  invalid doc source
@#[line:0,col:undefined]
^[[37m[17.03.2021, 07:34:50] ^[[39m^[[36m[homebridge-lgtv-2012a]^[[39m This plugin generated a warning from the characteristic 'Active Identifier': characteristic value expected $
^[[37m[17.03.2021, 07:34:50] ^[[39m^[[90m^[[36m[homebridge-lgtv-2012a]^[[39m^[[90m Error: ^[[39m
^[[90m    at ActiveIdentifier.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2032:105)^[[39m
^[[90m    at ActiveIdentifier.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1925:16)^[[39m
^[[90m    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1531:24^[[39m
^[[90m    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18^[[39m
^[[90m    at /usr/local/lib/node_modules/homebridge-lgtv-2012a/index.js:316:6^[[39m
^[[90m    at /usr/local/lib/node_modules/homebridge-lgtv-2012a/node_modules/lgtv-2012/index.js:209:24^[[39m
^[[90m    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-lgtv-2012a/node_modules/lgtv-2012/index.js:82:21)^[[39m
^[[90m    at ClientRequest.emit (events.js:315:20)^[[39m
^[[90m    at Socket.socketErrorListener (_http_client.js:469:9)^[[39m
^[[90m    at Socket.emit (events.js:315:20)^[[39m
^[[37m[17.03.2021, 07:34:58] ^[[39m^[[36m[MiAqaraPlatform]^[[39m ^[[90m[DEBUG][Revc]{"cmd":"report","model":"sensor_motion.aq2","sid":"158d0002b486ba","short_id":48434,"data":"{\$
^[[37m[17.03.2021, 07:34:58] ^[[39m^[[36m[RTV]^[[39m ^[[90m**Fakegato-timer: addData  Przedpokój Czujnik Ruchu { time: 1615962898, status: 0 }  immediate:  true^[[39m
^[[37m[17.03.2021, 07:34:58] ^[[39m^[[36m[RTV]^[[39m ^[[90m**Fakegato-timer: executeImmediateCallback**^[[39m
^[[37m[17.03.2021, 07:34:58] ^[[39m^[[36m[MiAqaraPlatform]^[[39m ^[[90m**Fakegato-timer callbackMotion:  Przedpokój Czujnik Ruchu , immediate:  true , entry:  { time: 1615962898,$
^[[37m[17.03.2021, 07:34:58] ^[[39m^[[36m[MiAqaraPlatform]^[[39m ^[[90mFirst entry Przedpokój Czujnik Ruchu: 0^[[39m
^[[37m[17.03.2021, 07:34:58] ^[[39m^[[36m[MiAqaraPlatform]^[[39m ^[[90mLast entry Przedpokój Czujnik Ruchu: c57^[[39m
^[[37m[17.03.2021, 07:34:58] ^[[39m^[[36m[MiAqaraPlatform]^[[39m ^[[90mUsed memory Przedpokój Czujnik Ruchu: c57^[[39m
^[[37m[17.03.2021, 07:34:58] ^[[39m^[[36m[MiAqaraPlatform]^[[39m ^[[90m116 Przedpokój Czujnik Ruchu: 1fbf050000000000731bfc2502 1301 1c01580cc00f00000000000000000101^[[39m
^[[37m[17.03.2021, 07:34:58] ^[[39m^[[36m[RTV]^[[39m ^[[90m** Fakegato-storage write FS file: /var/lib/homebridge/accessories/raspberrypi_Przedpokój Czujnik Ruchu_persist.json "f$
^[[37m[17.03.2021, 07:34:59] ^[[39m^[[36m[RTV]^[[39m Received MQTT: tele/Sonoffpow/SENSOR = {"Time":"2021-03-17T07:34:59","ENERGY":{"TotalStartTime":"2019-12-23T13:15:19","Total"$
^[[37m[17.03.2021, 07:34:59] ^[[39m^[[36m[RTV]^[[39m ^[[90m**Fakegato-timer: addData  RTV { time: 1615962899, power: 0 }  immediate:  false^[[39m
^[[37m[17.03.2021, 07:35:02] ^[[39m^[[36m[Philips TV]^[[39m ^[[90mEntering getPowerState with context: undefined and current value: false^[[39m
^[[37m[17.03.2021, 07:35:14] ^[[39m^[[36m[RTV]^[[39m Received MQTT: tele/Sonoffpow/SENSOR = {"Time":"2021-03-17T07:35:14","ENERGY":{"TotalStartTime":"2019-12-23T13:15:19","Total"$
^[[37m[17.03.2021, 07:35:14] ^[[39m^[[36m[RTV]^[[39m ^[[90m**Fakegato-timer: addData  RTV { time: 1615962914, power: 0 }  immediate:  false^[[39m
^[[37m[17.03.2021, 07:35:29] ^[[39m^[[36m[RTV]^[[39m Received MQTT: tele/Sonoffpow/SENSOR = {"Time":"2021-03-17T07:35:29","ENERGY":{"TotalStartTime":"2019-12-23T13:15:19","Total"$
^[[37m[17.03.2021, 07:35:29] ^[[39m^[[36m[RTV]^[[39m ^[[90m**Fakegato-timer: addData  RTV { time: 1615962929, power: 0 }  immediate:  false^[[39m
^[[37m[17.03.2021, 07:35:44] ^[[39m^[[36m[RTV]^[[39m Received MQTT: tele/Sonoffpow/SENSOR = {"Time":"2021-03-17T07:35:44","ENERGY":{"TotalStartTime":"2019-12-23T13:15:19","Total"$
^[[37m[17.03.2021, 07:35:44] ^[[39m^[[36m[RTV]^[[39m ^[[90m**Fakegato-timer: addData  RTV { time: 1615962944, power: 0 }  immediate:  false^[[39m
^[[37m[17.03.2021, 07:35:47] ^[[39m^[[36m[Philips TV]^[[39m ^[[90mEntering getPowerState with context: statuspoll and current value: false^[[39m
^[[37m[17.03.2021, 07:35:47] ^[[39m^[[36m[Philips TV]^[[39m ^[[90mEntering getMutedState with context: statuspoll and current state: false^[[39m
^[[37m[17.03.2021, 07:35:47] ^[[39m^[[36m[Philips TV]^[[39m ^[[90mEntering getVolumeLevel with context: statuspoll and current value: 0^[[39m
^[[37m[17.03.2021, 07:35:49] ^[[39m^[[36m[Philips TV]^[[39m ^[[90mgetPowerState - ERROR: ETIMEDOUT^[[39m
^[[37m[17.03.2021, 07:35:59] ^[[39m^[[36m[RTV]^[[39m Received MQTT: tele/Sonoffpow/SENSOR = {"Time":"2021-03-17T07:35:59","ENERGY":{"TotalStartTime":"2019-12-23T13:15:19","Total"$
^[[37m[17.03.2021, 07:35:59] ^[[39m^[[36m[RTV]^[[39m ^[[90m**Fakegato-timer: addData  RTV { time: 1615962959, power: 0 }  immediate:  false^[[39m
^[[37m[17.03.2021, 07:36:14] ^[[39m^[[36m[RTV]^[[39m Received MQTT: tele/Sonoffpow/SENSOR = {"Time":"2021-03-17T07:36:14","ENERGY":{"TotalStartTime":"2019-12-23T13:15:19","Total"$
^[[37m[17.03.2021, 07:36:14] ^[[39m^[[36m[RTV]^[[39m ^[[90m**Fakegato-timer: addData  RTV { time: 1615962974, power: 0 }  immediate:  false^[[39m
^[[37m[17.03.2021, 07:36:27] ^[[39m^[[36m[HomebridgeADB]^[[39m KII - Reconnecting
^[[37m[17.03.2021, 07:36:27] ^[[39m^[[36m[HomebridgeADB]^[[39m KII - Reconnecting
^[[37m[17.03.2021, 07:36:27] ^[[39m^[[36m[HomebridgeADB]^[[39m KII - Reconnecting
^[[37m[17.03.2021, 07:36:27] ^[[39m^[[36m[HomebridgeADB]^[[39m KII - Can't get media status
^[[37m[17.03.2021, 07:36:27] ^[[39m^[[36m[HomebridgeADB]^[[39m KII - Reconnecting
^[[37m[17.03.2021, 07:36:27] ^[[39m^[[36m[HomebridgeADB]^[[39m KII - Reconnecting
^[[37m[17.03.2021, 07:36:27] ^[[39m^[[31mTypeError: this.log.infor is not a function^[[39m
^[[31m    at /usr/local/lib/node_modules/homebridge-adb/index.js:695:15^[[39m
^[[31m    at ChildProcess.exithandler (child_process.js:315:5)^[[39m
^[[31m    at ChildProcess.emit (events.js:315:20)^[[39m
^[[31m    at maybeClose (internal/child_process.js:1048:16)^[[39m
^[[31m    at Socket.<anonymous> (internal/child_process.js:439:11)^[[39m
^[[31m    at Socket.emit (events.js:315:20)^[[39m
^[[31m    at Pipe.<anonymous> (net.js:673:12)^[[39m
^[[37m[17.03.2021, 07:36:27] ^[[39mGot SIGTERM, shutting down Homebridge...
^[[37m[17.03.2021, 07:36:27] ^[[39m^[[36m[HomebridgeADB]^[[39m KII - Reconnecting
^[[37m[17.03.2021, 07:36:27] ^[[39m^[[31mTypeError: this.log.infor is not a function^[[39m
^[[31m    at /usr/local/lib/node_modules/homebridge-adb/index.js:695:15^[[39m
^[[31m    at ChildProcess.exithandler (child_process.js:315:5)^[[39m
^[[31m    at ChildProcess.emit (events.js:315:20)^[[39m
^[[31m    at maybeClose (internal/child_process.js:1048:16)^[[39m
^[[31m    at Socket.<anonymous> (internal/child_process.js:439:11)^[[39m
^[[31m    at Socket.emit (events.js:315:20)^[[39m
^[[31m    at Pipe.<anonymous> (net.js:673:12)^[[39m
^[[37m[17.03.2021, 07:36:27] ^[[39mGot SIGTERM, shutting down child bridge process...
^[[37m[17.03.2021, 07:36:28] ^[[39m^[[36m[HomebridgeADB]^[[39m KII - Can't get media status
^[[37m[17.03.2021, 07:36:29] ^[[39m^[[36m[RTV]^[[39m Received MQTT: tele/Sonoffpow/SENSOR = {"Time":"2021-03-17T07:36:29","ENERGY":{"TotalStartTime":"2019-12-23T13:15:19","Total"$
^[[37m[17.03.2021, 07:36:29] ^[[39m^[[36m[RTV]^[[39m ^[[90m**Fakegato-timer: addData  RTV { time: 1615962989, power: 0 }  immediate:  false^[[39m
^[[37m[17.03.2021, 07:36:29] ^[[39m^[[36m[HomebridgeADB]^[[39m KII - Can't get media status
^[[37m[17.03.2021, 07:36:30] ^[[39m^[[36m[HomebridgeADB]^[[39m KII - Can't get media status
^[[37m[17.03.2021, 07:36:31] ^[[39m^[[36m[HomebridgeADB]^[[39m KII - Can't get media status
^[[37m[17.03.2021, 07:36:32] ^[[39m^[[36m[HomebridgeADB]^[[39m KII - Can't get media status
^[[37m[17.03.2021, 07:36:32]^[[0m ^[[36m[HB Supervisor]^[[0m Homebridge Process Ended. Code: 143, Signal: null
^[[37m[17.03.2021, 07:36:37]^[[0m ^[[36m[HB Supervisor]^[[0m Restarting Homebridge...
^[[37m[17.03.2021, 07:36:37]^[[0m ^[[36m[HB Supervisor]^[[0m Starting Homebridge with extra flags: -I -D
^[[37m[17.03.2021, 07:36:37]^[[0m ^[[36m[HB Supervisor]^[[0m Started Homebridge v1.3.3 with PID: 4775
Initializing HAP-NodeJS v0.9.3...

**Comment by pawelosin** [comment]
I updated the plugin but nothing has changed. Still the device does not respond until I restart homebridge and even though I turn the device off in the home app, it appears turned on after a few seconds.

**Comment by dwaan** [comment]
Yes. Correct I haven’t figure out how to fix the initial issue. Just fixing the restarting problem because plug-in error.

**Comment by pawelosin** [comment]
After update to v 1.4.3 works fine for me.

**Comment by snarknesor** [comment]
same. thanks
