### ISSUE TITLE
Remote Control D pad?

### ISSUE THREAD

**Issue by Clickbaitcake** [dwaan/homebridge-adb#3]
Hello,

The Readme mentions the ability to send up down left right commands via ADB but I do not see this functionality in HomeKit or via remote app on iOS. Should the accessory be registering some sort of remote control support? Should the screen be driveable from the HomeKit App?

**Comment by dwaan** [comment]
You can use the remote functionality from your iOS control center. 
![A4329F21-3DC6-4B76-BFAC-FEA219B63FE4](https://user-images.githubusercontent.com/1238465/92201616-b13f5400-ee85-11ea-96bd-a918ea58aa9f.jpeg)

After you press it, it will display the remote like this. If there’s no remote control icon in your control center, make sure you add it first from the Settings -> Control Center. 

![AECE3BBE-A92B-4D30-8829-0A3F3377AB37](https://user-images.githubusercontent.com/1238465/92201747-01b6b180-ee86-11ea-941f-9e886d7de354.jpeg)

After that you can control your android device using the remote like when you’re using regular physical remote, including volume control when you pressed the iOS device volume buttons.  

It won’t appear in Apple TV remote or Remote app as it’s not an Apple TV.

**Comment by Clickbaitcake** [comment]
Thank you for explination @dwaan  could this be added to the ReadMe?

**Comment by dwaan** [comment]
No problem. I added it to the readme.
