### ISSUE TITLE
Plugin slows down Homebridge Error

### ISSUE THREAD

**Issue by Strolch46** [dwaan/homebridge-adb#31]
This plugin slows down Homebridge. The read handler for the characteristic 'Active' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.

Have this Plugin installed and connected with a FireTV 4K Stick
It works otherwise.

**Comment by dwaan** [comment]
Thank you for head up. The new version eliminate those warning messages now, hopefully.
