### ISSUE TITLE
[Enhancement Request] Allow selection of Accessory Category

### ISSUE THREAD

**Issue by muzzymate** [dwaan/homebridge-adb#33]
By changing the [Accessory Category type value](https://developers.homebridge.io/#/categories), newer versions of iOS and Homebridge support exposing television-like devices as either televisions, audio receivers, set top boxes, or streaming sticks. I use Homebridge-ADB to expose my FireTV Cube and Sticks to Homekit to allow for control of the devices through the Remote Widget or Home app.

Rather than showing the FireTV Stick as a television, it made more sense in my particular circumstance to show it as an actual streaming stick icon. To do so, I made a minor change in my location installation of the index.js file from 

`		this.tv.category = this.api.hap.Categories.TELEVISION;` 

to

`		this.tv.category = this.api.hap.Categories.TV_STREAMING_STICK;` 

After removing the TV accessory and re-adding, the devices now appears as an actual streaming stick in the Home app. 

I'm happy to continue making this edit to my local installation as Homebridge-ADB develops further, but I thought others could benefit from choosing what device type the accessory appears as in the Home app. However, changing Homebridge-ADB to always display as a streaming icon is not universal for all devices that can be exposed using Homebridge-ADB. Unfortunately, making that dynamic based on user configuration is beyond my technical ability, so I'm writing it here as enhancement for consideration. Even in my own installation, it would be nice to expose the 4 FireTV Sticks as streaming sticks but then expose the FireTV Cube as a set top box. 

Thanks!

Edit: For illustration purposes, uploading examples of the icons used in the Home app for the other [Access Category Types](https://developers.homebridge.io/#/categories).

**TV_SET_TOP_BOX**

![IMG_0602](https://user-images.githubusercontent.com/46382192/109836852-95d5bb80-7c12-11eb-9f84-6fba288acc70.jpeg)

**TV_STREAMING_STICK**

![IMG_0601](https://user-images.githubusercontent.com/46382192/109836953-ae45d600-7c12-11eb-929e-1eca0b2dc686.jpeg)

**AUDIO_RECEIVER**    (not sure if it makes sense for Homebridge-ADB, but since I mentioned the type above)

![IMG_0605](https://user-images.githubusercontent.com/46382192/109836998-b9006b00-7c12-11eb-8417-afd1792b56e3.jpeg)

**Comment by dwaan** [comment]
Thank you for the head up, will going to accommodate it in the future release.

**Comment by dwaan** [comment]
New version add this feature. Thank you.
