### ISSUE TITLE
Wake on lan to turn the device on

### ISSUE THREAD

**Issue by pawelosin** [dwaan/homebridge-adb#35]
Hi, is there a way to use wakeonlan command to turn the device on?

**Comment by dwaan** [comment]
Currently this feature is not implemented yet. But will consider adding this in future release.

**Comment by danFontan** [comment]
Hi dwaan, this feature would be a great enhancement. If it helps, the following code works fine for me on the terminal while the TV is in sleep/standby mode:

adb -s <DEVICE-IP> shell "input keyevent KEYCODE_WAKEUP"

**Comment by dwaan** [comment]
> Hi dwaan, this feature would be a great enhancement. If it helps, the following code works fine for me on the terminal while the TV is in sleep/standby mode:
> 
> adb -s shell "input keyevent KEYCODE_WAKEUP"

Hey, Thank you. That’s the command that this plugins use right now.

The wakeonlan could be useful for some device that disconnected from network when it sleep, I think.

**Comment by pawelosin** [comment]
I changed the command in index.js to 

// When it sleep, wake it up
 exec(`wakeonlan XX:XX:XX:XX:XX:XX`, (err, stdout, stderr) => {

(XX:XX:XX:XX:XX:XX is mac address of my device)
and now it works as I wanted.

**Comment by dwaan** [comment]
Closing this issues as it's implemented in newer version, currently in beta.
