### ISSUE TITLE
PlayBack Sensor 

### ISSUE THREAD

**Issue by Stef1972** [dwaan/homebridge-adb#36]
HI, I'm using an Amazon Firestik configured with homebridge-adb and I appreciated the PlayBack sensor. But I've noticed an issue.
The sensor is working fine if you play a movie (it become active) and if you pause (it become inactive).
But if you are playing a movie and you decide to stop it pressing the button Back (instead of home) the Sensor remain active and the firestick do not respond anymore: if you tray to turn it of from homebridge you receive an error: 

[Homebridge UI] [HapClient] [192.168.1.48:41283 (0F:27:15:6A:E0:B2)] Failed to set value for FireStick B436.

Again: all is working fine if you use the Home button on the firestick remote control. If you press "back" on the remote control the sensor remain active and the forested doesn't work anymore

Thanks

**Comment by dwaan** [comment]
Thank you for the bugs report, will fix this soon.

**Comment by dwaan** [comment]
Could you provide more information: like what apps causing it if it's only in one app? what other output before the output you mention before? It seems like I can't recreate your error right now.

**Comment by Stef1972** [comment]
I notice it using Amazon Prime on the FireStick. It happens:
- If I press back button while playing to come back to home instead of pressing pause+home or just home
- If I turn off the firestik via remote control without pausing the movie or coming back to home. In this case the accessory Firestick become grey (turned off) while the sensor remain active

I didn't test other app for the moment

**Comment by dwaan** [comment]
The latest update might solve this problem, please try it and let me know the result.

**Comment by Stef1972** [comment]
Yes the problem is solved with Amazon Prime
With the app Disney+ the sensor never became active

**Comment by dwaan** [comment]
> Yes the problem is solved with Amazon Prime
> With the app Disney+ the sensor never became active

OK, it seems that your Disney+ might output different messages then mine.  Do you mind to run this command in your computer when you're playing video in Disney+ app?

`adb -s your-device-ip shell "dumpsys media_session | grep state=PlaybackState"`

Send the output here, so I can examine the output.

**Comment by Stef1972** [comment]
here it is:

state=PlaybackState {state=2, position=0, buffered position=0, speed=0.0, updated=347585832, actions=38, custom actions=[], active item id=-1, error=null}
  state=PlaybackState {state=3, position=25966, buffered position=83082, speed=1.0, updated=409092734, actions=2360175, custom actions=[], active item id=1, error=null}
    state=PlaybackState {state=3, position=25966, buffered position=83082, speed=1.0, updated=409092734, actions=2360175, custom actions=[], active item id=1, error=null}
    state=PlaybackState {state=2, position=0, buffered position=0, speed=0.0, updated=347585832, actions=38, custom actions=[], active item id=-1, error=null}

**Comment by Stef1972** [comment]
I was looking to understand if the problem was related to Disney+ only and I payed video on youtube app. when I did that the sensor turned on correctly. Then I pause the video and the sensor remains on, I came back home and the sensor remains on. I turned off the fire stick and the sensor remains on!

this is the log while the fire stick is off (it seems like youtube's never stopped)
Hope it helps.

MEDIA SESSION SERVICE (dumpsys media_session)

3 sessions listeners.
3 Sessions:
Vizzini_2.0.10900.0:MediaButtonController com.amazon.vizzini/Vizzini_2.0.10900.0:MediaButtonController
  ownerPid=31828, ownerUid=32092, userId=0
  package=com.amazon.vizzini
  launchIntent=null
  mediaButtonReceiver=null
  active=true
  flags=2
  rating type=0
  controllers: 0
  state=null
  audioAttrs=AudioAttributes: usage=1 content=0 flags=0x0 tags=
  volumeType=1, controlType=2, max=0, current=0
  metadata:size=0, description=null
  queueTitle=null, size=0

starboard_media com.amazon.firetv.youtube/starboard_media
  ownerPid=5185, ownerUid=10025, userId=0
  package=com.amazon.firetv.youtube
  launchIntent=null
  mediaButtonReceiver=null
  active=false
  flags=2
  rating type=0
  controllers: 0
  state=PlaybackState {state=3, position=0, buffered position=0, speed=0.0, updated=410850228, actions=4, custom actions=[], active item id=-1, error=null}
  audioAttrs=AudioAttributes: usage=1 content=0 flags=0x0 tags=
  volumeType=1, controlType=2, max=0, current=0
  metadata:size=4, description=null, null, null
  queueTitle=null, size=0

PrimeVideo-MediaSession com.amazon.avod/PrimeVideo-MediaSession
  ownerPid=5633, ownerUid=32047, userId=0
  package=com.amazon.avod
  launchIntent=null
  mediaButtonReceiver=PendingIntent{1f490cd4: PendingIntentRecord{28785b0e com.amazon.avod broadcastIntent}}
  active=false
  flags=2
  rating type=0
  controllers: 2
  state=PlaybackState {state=2, position=15712, buffered position=0, speed=0.0, updated=410700034, actions=173350, custom actions=[], active item id=-1, error=null}
  audioAttrs=AudioAttributes: usage=1 content=0 flags=0x0 tags=
  volumeType=1, controlType=2, max=0, current=0
  metadata:size=12, description=Episodio 8, null, null
  queueTitle=null, size=0

Global priority session is null
Sessions Stack - have 3 sessions:
  Vizzini_2.0.10900.0:MediaButtonController com.amazon.vizzini/Vizzini_2.0.10900.0:MediaButtonController
    ownerPid=31828, ownerUid=32092, userId=0
    package=com.amazon.vizzini
    launchIntent=null
    mediaButtonReceiver=null
    active=true
    flags=2
    rating type=0
    controllers: 0
    state=null
    audioAttrs=AudioAttributes: usage=1 content=0 flags=0x0 tags=
    volumeType=1, controlType=2, max=0, current=0
    metadata:size=0, description=null
    queueTitle=null, size=0

  PrimeVideo-MediaSession com.amazon.avod/PrimeVideo-MediaSession
    ownerPid=5633, ownerUid=32047, userId=0
    package=com.amazon.avod
    launchIntent=null
    mediaButtonReceiver=PendingIntent{1f490cd4: PendingIntentRecord{28785b0e com.amazon.avod broadcastIntent}}
    active=false
    flags=2
    rating type=0
    controllers: 2
    state=PlaybackState {state=2, position=15712, buffered position=0, speed=0.0, updated=410700034, actions=173350, custom actions=[], active item id=-1, error=null}
    audioAttrs=AudioAttributes: usage=1 content=0 flags=0x0 tags=
    volumeType=1, controlType=2, max=0, current=0
    metadata:size=12, description=Episodio 8, null, null
    queueTitle=null, size=0

  starboard_media com.amazon.firetv.youtube/starboard_media
    ownerPid=5185, ownerUid=10025, userId=0
    package=com.amazon.firetv.youtube
    launchIntent=null
    mediaButtonReceiver=null
    active=false
    flags=2
    rating type=0
    controllers: 0
    state=PlaybackState {state=3, position=0, buffered position=0, speed=0.0, updated=410850228, actions=4, custom actions=[], active item id=-1, error=null}
    audioAttrs=AudioAttributes: usage=1 content=0 flags=0x0 tags=
    volumeType=1, controlType=2, max=0, current=0
    metadata:size=4, description=null, null, null
    queueTitle=null, size=0

User Records:
Record for user 0
  MediaButtonReceiver:PendingIntent{1f490cd4: PendingIntentRecord{28785b0e com.amazon.avod broadcastIntent}}
  3 Sessions:
  com.amazon.vizzini/Vizzini_2.0.10900.0:MediaButtonController
  com.amazon.firetv.youtube/starboard_media
  com.amazon.avod/PrimeVideo-MediaSession

**Comment by dwaan** [comment]
Android ADB document said that the fist `state=PlaybackState` should indicate playback status. We're looking for first `state=PlaybackState` with `state=3` as a sign of media is playing. 

Your `dumpsys media_session`  output with the first result of `state=PlaybackState` is `state=3`  meaning current media is playing.

While, your  `dumpsys media_session | grep ...`  output with the first result of `state=PlaybackState` is `state=2` meaning current media is pausing. 

If this is the same output, then we found the culprit that cause wrong reading by the plugins. The plugins use the output from  `dumpsys media_session | grep ...` because it's shorter, so the plugins doesn't have to download large data.

**Comment by Stef1972** [comment]
Hi Dwaan, with the last update 1.4.3 the sensor doesn’t work anymore nor with Prime nor with Disney +. Installing back the 1.4.2 Prime start to work again

**Comment by dwaan** [comment]
I'm using a new ADB command to detect playback, it's work properly for app like Disney+ or Cartoon Network that  didn't report their status to `dumpsys media_session`, at least in some of device that I test.

What I use right now is a command like this `dumpsys audio | grep 'player piid' | tail -10`, it report any audio playback. But maybe different devices output differently. if you can share your output for that command with those two apps, I'll be gladly to examine that.

**Comment by Stef1972** [comment]
can you please give me the exact command ?

**Comment by Stef1972** [comment]
pi@homebridge:/var/lib/homebridge $ adb shell "dumpsys audio"

Audio Focus stack entries (last is top of stack):
  source:android.os.BinderProxy@e67d9b8 -- pack: com.amazon.avod -- client: com.amazon.media.AmazonAudioManager@314ebd8dcom.amazon.avod.playbackclient.feature.audiofocus.AudioFocusManager$GlobalAudioFocusChangeListener@2455db42 -- gain: GAIN -- flags:  -- loss: none -- uid: 32047 -- attr: AudioAttributes: usage=1 content=2 flags=0x0 tags=

 Notify on duck: true


Remote Control stack entries (last is top of stack):

Remote Control Client stack entries (last is top of stack):

Current remote control generation ID = 0

Remote Volume State:
  has remote: false
  is remote active: false
  rccId: -1
  volume handling: PLAYBACK_VOLUME_VARIABLE(1)
  volume: 15
  volume steps: 15

Remote Control Display list entries:

Stream volumes (device: index)
- STREAM_VOICE_CALL:
   Mute count: 0
   Max: 5
   Current: 2000 (usb_accessory): 5, 1000 (digital_dock): 5, 800 (analog_dock): 5, 400 (hdmi): 5, 40000000 (default): 5, 40 (bt_sco_carkit): 5, 80 (bt_a2dp): 5, 100 (bt_a2dp_hp): 5, 200 (bt_a2dp_spk): 5, 2000000 (proxy): 5, 400000 (speaker_safe): 5, 8000 (remote_submix): 5, 4000 (usb_device): 5, 1 (earpiece): 5, 10000 (telephony_tx): 5, 2 (speaker): 5, 20000 (line): 5, 4 (headset): 5, 40000 (hmdi_arc): 5, 80000 (spdif): 5, 8 (headphone): 5, 10 (bt_sco): 5, 100000 (fm_transmitter): 5, 20 (bt_sco_hs): 5, 200000 (aux_line): 5
- STREAM_SYSTEM:
   Mute count: 0
   Max: 7
   Current: 2000 (usb_accessory): 7, 1000 (digital_dock): 7, 800 (analog_dock): 7, 400 (hdmi): 7, 40000000 (default): 7, 40 (bt_sco_carkit): 7, 80 (bt_a2dp): 7, 100 (bt_a2dp_hp): 7, 200 (bt_a2dp_spk): 7, 2000000 (proxy): 7, 400000 (speaker_safe): 7, 8000 (remote_submix): 7, 4000 (usb_device): 7, 1 (earpiece): 7, 10000 (telephony_tx): 7, 2 (speaker): 7, 20000 (line): 7, 4 (headset): 7, 40000 (hmdi_arc): 7, 80000 (spdif): 7, 8 (headphone): 7, 10 (bt_sco): 7, 100000 (fm_transmitter): 7, 20 (bt_sco_hs): 7, 200000 (aux_line): 7
- STREAM_RING:
   Mute count: 0
   Max: 7
   Current: 2000 (usb_accessory): 7, 1000 (digital_dock): 7, 800 (analog_dock): 7, 400 (hdmi): 7, 40000000 (default): 7, 40 (bt_sco_carkit): 7, 80 (bt_a2dp): 7, 100 (bt_a2dp_hp): 7, 200 (bt_a2dp_spk): 7, 2000000 (proxy): 7, 400000 (speaker_safe): 7, 8000 (remote_submix): 7, 4000 (usb_device): 7, 1 (earpiece): 7, 10000 (telephony_tx): 7, 2 (speaker): 7, 20000 (line): 7, 4 (headset): 7, 40000 (hmdi_arc): 7, 80000 (spdif): 7, 8 (headphone): 7, 10 (bt_sco): 7, 100000 (fm_transmitter): 7, 20 (bt_sco_hs): 7, 200000 (aux_line): 7
- STREAM_MUSIC:
   Mute count: 0
   Max: 15
   Current: 2000000 (proxy): 15, 400000 (speaker_safe): 15, 8000 (remote_submix): 15, 4000 (usb_device): 15, 40000000 (default): 15, 40 (bt_sco_carkit): 15, 80 (bt_a2dp): 15, 100 (bt_a2dp_hp): 15, 200 (bt_a2dp_spk): 15, 400 (hdmi): 15, 800 (analog_dock): 15, 1000 (digital_dock): 15, 2000 (usb_accessory): 15, 1 (earpiece): 15, 10000 (telephony_tx): 15, 2 (speaker): 15, 20000 (line): 15, 4 (headset): 15, 40000 (hmdi_arc): 15, 8 (headphone): 15, 80000 (spdif): 15, 10 (bt_sco): 15, 100000 (fm_transmitter): 15, 20 (bt_sco_hs): 15, 200000 (aux_line): 15
- STREAM_ALARM:
   Mute count: 0
   Max: 7
   Current: 2000 (usb_accessory): 7, 1000 (digital_dock): 7, 800 (analog_dock): 7, 400 (hdmi): 7, 40000000 (default): 7, 40 (bt_sco_carkit): 7, 80 (bt_a2dp): 7, 100 (bt_a2dp_hp): 7, 200 (bt_a2dp_spk): 7, 2000000 (proxy): 7, 400000 (speaker_safe): 7, 8000 (remote_submix): 7, 4000 (usb_device): 7, 1 (earpiece): 7, 10000 (telephony_tx): 7, 2 (speaker): 7, 20000 (line): 7, 4 (headset): 7, 40000 (hmdi_arc): 7, 80000 (spdif): 7, 8 (headphone): 7, 10 (bt_sco): 7, 100000 (fm_transmitter): 7, 20 (bt_sco_hs): 7, 200000 (aux_line): 7
- STREAM_NOTIFICATION:
   Mute count: 0
   Max: 7
   Current: 2000 (usb_accessory): 7, 1000 (digital_dock): 7, 800 (analog_dock): 7, 400 (hdmi): 7, 40000000 (default): 7, 40 (bt_sco_carkit): 7, 80 (bt_a2dp): 7, 100 (bt_a2dp_hp): 7, 200 (bt_a2dp_spk): 7, 2000000 (proxy): 7, 400000 (speaker_safe): 7, 8000 (remote_submix): 7, 4000 (usb_device): 7, 1 (earpiece): 7, 10000 (telephony_tx): 7, 2 (speaker): 7, 20000 (line): 7, 4 (headset): 7, 40000 (hmdi_arc): 7, 80000 (spdif): 7, 8 (headphone): 7, 10 (bt_sco): 7, 100000 (fm_transmitter): 7, 20 (bt_sco_hs): 7, 200000 (aux_line): 7
- STREAM_BLUETOOTH_SCO:
   Mute count: 0
   Max: 15
   Current: 2000 (usb_accessory): 15, 1000 (digital_dock): 15, 800 (analog_dock): 15, 400 (hdmi): 15, 40000000 (default): 15, 40 (bt_sco_carkit): 15, 80 (bt_a2dp): 15, 100 (bt_a2dp_hp): 15, 200 (bt_a2dp_spk): 15, 2000000 (proxy): 15, 400000 (speaker_safe): 15, 8000 (remote_submix): 15, 4000 (usb_device): 15, 1 (earpiece): 15, 10000 (telephony_tx): 15, 2 (speaker): 15, 20000 (line): 15, 4 (headset): 15, 40000 (hmdi_arc): 15, 80000 (spdif): 15, 8 (headphone): 15, 10 (bt_sco): 15, 100000 (fm_transmitter): 15, 20 (bt_sco_hs): 15, 200000 (aux_line): 15
- STREAM_SYSTEM_ENFORCED:
   Mute count: 0
   Max: 7
   Current: 2000 (usb_accessory): 7, 1000 (digital_dock): 7, 800 (analog_dock): 7, 400 (hdmi): 7, 40000000 (default): 7, 40 (bt_sco_carkit): 7, 80 (bt_a2dp): 7, 100 (bt_a2dp_hp): 7, 200 (bt_a2dp_spk): 7, 2000000 (proxy): 7, 400000 (speaker_safe): 7, 8000 (remote_submix): 7, 4000 (usb_device): 7, 1 (earpiece): 7, 10000 (telephony_tx): 7, 2 (speaker): 7, 20000 (line): 7, 4 (headset): 7, 40000 (hmdi_arc): 7, 80000 (spdif): 7, 8 (headphone): 7, 10 (bt_sco): 7, 100000 (fm_transmitter): 7, 20 (bt_sco_hs): 7, 200000 (aux_line): 7
- STREAM_DTMF:
   Mute count: 0
   Max: 15
   Current: 2000 (usb_accessory): 15, 1000 (digital_dock): 15, 800 (analog_dock): 15, 400 (hdmi): 15, 40000000 (default): 15, 40 (bt_sco_carkit): 15, 80 (bt_a2dp): 15, 100 (bt_a2dp_hp): 15, 200 (bt_a2dp_spk): 15, 2000000 (proxy): 15, 400000 (speaker_safe): 15, 8000 (remote_submix): 15, 4000 (usb_device): 15, 1 (earpiece): 15, 10000 (telephony_tx): 15, 2 (speaker): 15, 20000 (line): 15, 4 (headset): 15, 40000 (hmdi_arc): 15, 80000 (spdif): 15, 8 (headphone): 15, 10 (bt_sco): 15, 100000 (fm_transmitter): 15, 20 (bt_sco_hs): 15, 200000 (aux_line): 15
- STREAM_TTS:
   Mute count: 0
   Max: 15
   Current: 2000 (usb_accessory): 15, 1000 (digital_dock): 15, 800 (analog_dock): 15, 400 (hdmi): 15, 40000000 (default): 15, 40 (bt_sco_carkit): 15, 80 (bt_a2dp): 15, 100 (bt_a2dp_hp): 15, 200 (bt_a2dp_spk): 15, 2000000 (proxy): 15, 400000 (speaker_safe): 15, 8000 (remote_submix): 15, 4000 (usb_device): 15, 1 (earpiece): 15, 10000 (telephony_tx): 15, 2 (speaker): 15, 20000 (line): 15, 4 (headset): 15, 40000 (hmdi_arc): 15, 80000 (spdif): 15, 8 (headphone): 15, 10 (bt_sco): 15, 100000 (fm_transmitter): 15, 20 (bt_sco_hs): 15, 200000 (aux_line): 15

- mute affected streams = 0x2e

Ringer mode: 
- mode (internal) = NORMAL
- mode (external) = NORMAL
- ringer mode affected streams = 0x80
- ringer mode muted streams = 0x0
- delegate = ZenModeHelper

Audio routes:
  mMainType=0x8
  mBluetoothName=Device NOT Connected

Other state:
  mVolumeController=VolumeController(android.os.BinderProxy@153463d0,mVisible=false)
  mSafeMediaVolumeState=SAFE_MEDIA_VOLUME_ACTIVE
  mSafeMediaVolumeIndex=100
  mPendingVolumeCommand=null
  mMusicActiveMs=0
  mMcc=0
  mHasVibrator=false

Audio policies:

**Comment by dwaan** [comment]
Hi. 

Can you run this instead `adb shell "dumpsys audio | grep 'player piid' | tail -10"`

the log seem truncated.

**Comment by Stef1972** [comment]
pi@homebridge:/var/lib/homebridge $ adb shell "dumpsys audio | grep 'player piid' | tail -10"
/system/bin/sh: tail: not found

-----------------------------

pi@homebridge:/var/lib/homebridge $ adb shell "dumpsys audio | grep 'player piid'"
pi@homebridge:/var/lib/homebridge $ 

-------------------------------

pi@homebridge:/var/lib/homebridge $ adb shell "dumpsys audio"

Audio Focus stack entries (last is top of stack):
source:android.os.BinderProxy@e67d9b8 -- pack: com.amazon.avod -- client: com.amazon.media.AmazonAudioManager@314ebd8dcom.amazon.avod.playbackclient.feature.audiofocus.AudioFocusManager$GlobalAudioFocusChangeListener@2455db42 -- gain: GAIN -- flags: -- loss: none -- uid: 32047 -- attr: AudioAttributes: usage=1 content=2 flags=0x0 tags=

Notify on duck: true

Remote Control stack entries (last is top of stack):

Remote Control Client stack entries (last is top of stack):

Current remote control generation ID = 0

Remote Volume State:
has remote: false
is remote active: false
rccId: -1
volume handling: PLAYBACK_VOLUME_VARIABLE(1)
volume: 15
volume steps: 15

Remote Control Display list entries:

Stream volumes (device: index)

STREAM_VOICE_CALL:
Mute count: 0
Max: 5
Current: 2000 (usb_accessory): 5, 1000 (digital_dock): 5, 800 (analog_dock): 5, 400 (hdmi): 5, 40000000 (default): 5, 40 (bt_sco_carkit): 5, 80 (bt_a2dp): 5, 100 (bt_a2dp_hp): 5, 200 (bt_a2dp_spk): 5, 2000000 (proxy): 5, 400000 (speaker_safe): 5, 8000 (remote_submix): 5, 4000 (usb_device): 5, 1 (earpiece): 5, 10000 (telephony_tx): 5, 2 (speaker): 5, 20000 (line): 5, 4 (headset): 5, 40000 (hmdi_arc): 5, 80000 (spdif): 5, 8 (headphone): 5, 10 (bt_sco): 5, 100000 (fm_transmitter): 5, 20 (bt_sco_hs): 5, 200000 (aux_line): 5

STREAM_SYSTEM:
Mute count: 0
Max: 7
Current: 2000 (usb_accessory): 7, 1000 (digital_dock): 7, 800 (analog_dock): 7, 400 (hdmi): 7, 40000000 (default): 7, 40 (bt_sco_carkit): 7, 80 (bt_a2dp): 7, 100 (bt_a2dp_hp): 7, 200 (bt_a2dp_spk): 7, 2000000 (proxy): 7, 400000 (speaker_safe): 7, 8000 (remote_submix): 7, 4000 (usb_device): 7, 1 (earpiece): 7, 10000 (telephony_tx): 7, 2 (speaker): 7, 20000 (line): 7, 4 (headset): 7, 40000 (hmdi_arc): 7, 80000 (spdif): 7, 8 (headphone): 7, 10 (bt_sco): 7, 100000 (fm_transmitter): 7, 20 (bt_sco_hs): 7, 200000 (aux_line): 7

STREAM_RING:
Mute count: 0
Max: 7
Current: 2000 (usb_accessory): 7, 1000 (digital_dock): 7, 800 (analog_dock): 7, 400 (hdmi): 7, 40000000 (default): 7, 40 (bt_sco_carkit): 7, 80 (bt_a2dp): 7, 100 (bt_a2dp_hp): 7, 200 (bt_a2dp_spk): 7, 2000000 (proxy): 7, 400000 (speaker_safe): 7, 8000 (remote_submix): 7, 4000 (usb_device): 7, 1 (earpiece): 7, 10000 (telephony_tx): 7, 2 (speaker): 7, 20000 (line): 7, 4 (headset): 7, 40000 (hmdi_arc): 7, 80000 (spdif): 7, 8 (headphone): 7, 10 (bt_sco): 7, 100000 (fm_transmitter): 7, 20 (bt_sco_hs): 7, 200000 (aux_line): 7

STREAM_MUSIC:
Mute count: 0
Max: 15
Current: 2000000 (proxy): 15, 400000 (speaker_safe): 15, 8000 (remote_submix): 15, 4000 (usb_device): 15, 40000000 (default): 15, 40 (bt_sco_carkit): 15, 80 (bt_a2dp): 15, 100 (bt_a2dp_hp): 15, 200 (bt_a2dp_spk): 15, 400 (hdmi): 15, 800 (analog_dock): 15, 1000 (digital_dock): 15, 2000 (usb_accessory): 15, 1 (earpiece): 15, 10000 (telephony_tx): 15, 2 (speaker): 15, 20000 (line): 15, 4 (headset): 15, 40000 (hmdi_arc): 15, 8 (headphone): 15, 80000 (spdif): 15, 10 (bt_sco): 15, 100000 (fm_transmitter): 15, 20 (bt_sco_hs): 15, 200000 (aux_line): 15

STREAM_ALARM:
Mute count: 0
Max: 7
Current: 2000 (usb_accessory): 7, 1000 (digital_dock): 7, 800 (analog_dock): 7, 400 (hdmi): 7, 40000000 (default): 7, 40 (bt_sco_carkit): 7, 80 (bt_a2dp): 7, 100 (bt_a2dp_hp): 7, 200 (bt_a2dp_spk): 7, 2000000 (proxy): 7, 400000 (speaker_safe): 7, 8000 (remote_submix): 7, 4000 (usb_device): 7, 1 (earpiece): 7, 10000 (telephony_tx): 7, 2 (speaker): 7, 20000 (line): 7, 4 (headset): 7, 40000 (hmdi_arc): 7, 80000 (spdif): 7, 8 (headphone): 7, 10 (bt_sco): 7, 100000 (fm_transmitter): 7, 20 (bt_sco_hs): 7, 200000 (aux_line): 7

STREAM_NOTIFICATION:
Mute count: 0
Max: 7
Current: 2000 (usb_accessory): 7, 1000 (digital_dock): 7, 800 (analog_dock): 7, 400 (hdmi): 7, 40000000 (default): 7, 40 (bt_sco_carkit): 7, 80 (bt_a2dp): 7, 100 (bt_a2dp_hp): 7, 200 (bt_a2dp_spk): 7, 2000000 (proxy): 7, 400000 (speaker_safe): 7, 8000 (remote_submix): 7, 4000 (usb_device): 7, 1 (earpiece): 7, 10000 (telephony_tx): 7, 2 (speaker): 7, 20000 (line): 7, 4 (headset): 7, 40000 (hmdi_arc): 7, 80000 (spdif): 7, 8 (headphone): 7, 10 (bt_sco): 7, 100000 (fm_transmitter): 7, 20 (bt_sco_hs): 7, 200000 (aux_line): 7

STREAM_BLUETOOTH_SCO:
Mute count: 0
Max: 15
Current: 2000 (usb_accessory): 15, 1000 (digital_dock): 15, 800 (analog_dock): 15, 400 (hdmi): 15, 40000000 (default): 15, 40 (bt_sco_carkit): 15, 80 (bt_a2dp): 15, 100 (bt_a2dp_hp): 15, 200 (bt_a2dp_spk): 15, 2000000 (proxy): 15, 400000 (speaker_safe): 15, 8000 (remote_submix): 15, 4000 (usb_device): 15, 1 (earpiece): 15, 10000 (telephony_tx): 15, 2 (speaker): 15, 20000 (line): 15, 4 (headset): 15, 40000 (hmdi_arc): 15, 80000 (spdif): 15, 8 (headphone): 15, 10 (bt_sco): 15, 100000 (fm_transmitter): 15, 20 (bt_sco_hs): 15, 200000 (aux_line): 15

STREAM_SYSTEM_ENFORCED:
Mute count: 0
Max: 7
Current: 2000 (usb_accessory): 7, 1000 (digital_dock): 7, 800 (analog_dock): 7, 400 (hdmi): 7, 40000000 (default): 7, 40 (bt_sco_carkit): 7, 80 (bt_a2dp): 7, 100 (bt_a2dp_hp): 7, 200 (bt_a2dp_spk): 7, 2000000 (proxy): 7, 400000 (speaker_safe): 7, 8000 (remote_submix): 7, 4000 (usb_device): 7, 1 (earpiece): 7, 10000 (telephony_tx): 7, 2 (speaker): 7, 20000 (line): 7, 4 (headset): 7, 40000 (hmdi_arc): 7, 80000 (spdif): 7, 8 (headphone): 7, 10 (bt_sco): 7, 100000 (fm_transmitter): 7, 20 (bt_sco_hs): 7, 200000 (aux_line): 7

STREAM_DTMF:
Mute count: 0
Max: 15
Current: 2000 (usb_accessory): 15, 1000 (digital_dock): 15, 800 (analog_dock): 15, 400 (hdmi): 15, 40000000 (default): 15, 40 (bt_sco_carkit): 15, 80 (bt_a2dp): 15, 100 (bt_a2dp_hp): 15, 200 (bt_a2dp_spk): 15, 2000000 (proxy): 15, 400000 (speaker_safe): 15, 8000 (remote_submix): 15, 4000 (usb_device): 15, 1 (earpiece): 15, 10000 (telephony_tx): 15, 2 (speaker): 15, 20000 (line): 15, 4 (headset): 15, 40000 (hmdi_arc): 15, 80000 (spdif): 15, 8 (headphone): 15, 10 (bt_sco): 15, 100000 (fm_transmitter): 15, 20 (bt_sco_hs): 15, 200000 (aux_line): 15

STREAM_TTS:
Mute count: 0
Max: 15
Current: 2000 (usb_accessory): 15, 1000 (digital_dock): 15, 800 (analog_dock): 15, 400 (hdmi): 15, 40000000 (default): 15, 40 (bt_sco_carkit): 15, 80 (bt_a2dp): 15, 100 (bt_a2dp_hp): 15, 200 (bt_a2dp_spk): 15, 2000000 (proxy): 15, 400000 (speaker_safe): 15, 8000 (remote_submix): 15, 4000 (usb_device): 15, 1 (earpiece): 15, 10000 (telephony_tx): 15, 2 (speaker): 15, 20000 (line): 15, 4 (headset): 15, 40000 (hmdi_arc): 15, 80000 (spdif): 15, 8 (headphone): 15, 10 (bt_sco): 15, 100000 (fm_transmitter): 15, 20 (bt_sco_hs): 15, 200000 (aux_line): 15

mute affected streams = 0x2e

Ringer mode:

mode (internal) = NORMAL
mode (external) = NORMAL
ringer mode affected streams = 0x80
ringer mode muted streams = 0x0
delegate = ZenModeHelper
Audio routes:
mMainType=0x8
mBluetoothName=Device NOT Connected

Other state:
mVolumeController=VolumeController(android.os.BinderProxy@153463d0,mVisible=false)
mSafeMediaVolumeState=SAFE_MEDIA_VOLUME_ACTIVE
mSafeMediaVolumeIndex=100
mPendingVolumeCommand=null
mMusicActiveMs=0
mMcc=0
mHasVibrator=false

Audio policies:
pi@homebridge:/var/lib/homebridge $

**Comment by dwaan** [comment]
Ah. Thank you. Found the problem. tail command is not available in fire stick. Will update the plugins soon.

**Comment by Stef1972** [comment]
Hi 
Just update to version 1.4.4 --> playback sensor does not work: it never become active

**Comment by Stef1972** [comment]
I tried to uninstall and reinstall, to move to a child bridge and come back, to remove the accessory and the sensor from Home, to change their name... nothing seems to work: the sensor never turn on with any application.
Strange thing is that seems that also the previous 1.4.2 version has stop to work: with this version also the the sensor doesn't turn on...

do you need any specific log ? 

Thanks

**Comment by dwaan** [comment]
Yes, thank you. I need to formulated how to properly submit log message so everyone can help with this. Because so far, in my experience there is no exact way to detect playback status, some device output different log format.

**Comment by Stef1972** [comment]
ok, just tell me the command you want I launch to obtain the log you need.
Do you think is possible to use different way/commands to detect the playback status depending on the "category" selected in the config.json ?

**Comment by dwaan** [comment]
Merge into issue #46
