### ISSUE TITLE
Feature Request - Ignore Specific Apps

### ISSUE THREAD

**Issue by PixelBurstHD** [dwaan/homebridge-adb#39]
Thanks for all your hard work on this plugin so far!

Now you've got the sensor in based on playback, I'd love to see a way to exclude apps from the sensor such as Youtube so that when using for music it doesn't affect playback scenes for instance or Plex which has it's own Webhooks plugin for better control over scenes for TV/Movies etc.

**Comment by dwaan** [comment]
> Thanks for all your hard work on this plugin so far!
> 
> Now you've got the sensor in based on playback, I'd love to see a way to exclude apps from the sensor such as Youtube so that when using for music it doesn't affect playback scenes for instance or Plex which has it's own Webhooks plugin for better control over scenes for TV/Movies etc.

That's good idea. Will implement it in the future release.

**Comment by PixelBurstHD** [comment]
I see this is implemented, awesome stuff!
