### ISSUE TITLE
Incorrect command in Readme

### ISSUE THREAD

**Issue by Clickbaitcake** [dwaan/homebridge-adb#4]
The read me states the following information:

`To know current on screen app
 adb -s your-device-ip shell "dumpsys window windows | grep -E mFocusedApp"`

This command does not work. It should be:
`connect your-device-ip`

`adb shell dumpsys window windows | grep -E 'mCurrentFocus|mFocusedApp'`

**Comment by dwaan** [comment]
Mind to share your error output if you’re running my command in your server/computer? 

If you have more then one android devices connected to your server/computer, the parameter “-s your-device-ip” is needed for the adb to know which device it needed to run the command. I have successfully ran this command so far. 

I also learn that  quoting adb shell “command”, and put the grep inside the quote means that the grep will run inside the android, producing shorter output first and at the end it will produce less network traffic.

**Comment by Clickbaitcake** [comment]
Hello @dwaan 
I think I was typing this incorrectly. It does work but only after running connect command!
Maybe this issue can be closed? I think though a user would need to connect first?

**Comment by dwaan** [comment]
Yes, you're correct, the adb connect sometimes need to be run first. If I'm not wrong, using -s parameter also explicitly run adb connect.
