### ISSUE TITLE
Connected to ADB, But Cannot Control STB

### ISSUE THREAD

**Issue by ahmadnazirafiq** [dwaan/homebridge-adb#40]
I'm using a Long TV set-top-box ( a popular Android-based TV box in Asia). I used to be able to control input with this plugin. Now I've tried connecting it via adb connect <ip> its connected just fine but I can't control it at all.

**Log:**

> [01/04/2021, 12:40:52] [HomebridgeADB] Long TV - Can't make device sleep, or it's already sleep

> [01/04/2021, 12:40:53] [HomebridgeADB] Long TV - Can't make device sleep, or it's already sleep

> [01/04/2021, 12:41:02] [HomebridgeADB] Long TV - Can't make device wakeup, or it's already awake

> [01/04/2021,` 12:41:04] [HomebridgeADB] Long TV - Can't open - LemMovie

> [01/04/2021, 12:41:11] [HomebridgeADB] Long TV - Can't open - LemMovie

**ADB connection log:**

`nazir@Nazirs-iMac ~ % adb devices -l
List of devices attached
192.168.1.42:5555      device product:Hi3798MV200 model:LongTV_GN7501E device:Hi3798MV200 transport_id:133`

Tried connecting via both cable and WiFi, same issue. Help!

**Comment by ahmadnazirafiq** [comment]
UPDATE: Now its showing this when I ran adb devices -l

> 192.168.1.42:5555      offline product:Hi3798MV200 model:LongTV_GN7501E device:Hi3798MV200 transport_id:133

The box is still running and online. Hmm

**Comment by dwaan** [comment]
Did you device appear in Home app? Together with your inputs? 

If you run this command from homebridge server terminal: `adb -s 192.168.1.42 shell 'dumpsys power | grep mHoldingDisplay | cut -d = -f 2'`. What's the output?
