### ISSUE TITLE
Remove Number Prefix On Inputs

### ISSUE THREAD

**Issue by SpikePlayz** [dwaan/homebridge-adb#41]
Firstly, great plugin and thank you for your work. I setup inputs for my apps and for some reason the plugin tends to add number prefixes like 01., 02. etc.. for all of the different inputs with a random input called Other. Is there a way to remove this or toggle it off?

**Comment by dwaan** [comment]
For the prefix you can rename your input manually from the Home App. You can also hide any inputs by uncheck it from Home app.

**Comment by dwaan** [comment]
I added the option to remove the number and home-other inputs in new release.
