### ISSUE TITLE
Playback Sensor Support for Your Device

### ISSUE THREAD

**Issue by dwaan** [dwaan/homebridge-adb#43]
After several try, I come into conclusion that playback detection is a bit device specific. 

The problem is, `dumpsys` command's  output for detecting media playback are quite different between devices. If you wanted your device to be supported in playback sensor, please do this steps below.

1. Turn on your device.
2. Open any streaming or media app that you want.
3. Play any video.
4. Open ssh to your Homebridge server or open Terminal in Homebridge Config UI X.
5. Run this command: `adb -s DEVICE_IP_ADDRESS shell "dumpsys media_session"` copy paste the output to a text file called media_session.txt
6. Run this command: `adb -s DEVICE_IP_ADDRESS shell "dumpsys audio"` copy paste the output to a text file called audio.txt
7. Note: in my experience most of apps will appear in `dumpsys media_session` which is the preferable way to detect, but some apps (like Disney+, Cartoon Network) will appear in `dumpsys audio`

After that, please create an issue with provided template.

Current supported device:
1. NVIDIA Shield

**Comment by Stef1972** [comment]
[audio.txt](https://github.com/dwaan/homebridge-adb/files/6389870/audio.txt)
[media_session.txt](https://github.com/dwaan/homebridge-adb/files/6389871/media_session.txt)
