### ISSUE TITLE
Fire TV 4k stick doesn't appear in home app ?

### ISSUE THREAD

**Issue by mrota83** [dwaan/homebridge-adb#44]
Hi' 

I have a fire tv 4k stick and i can't add to the home app.

Im running hoobs with the adb plugin from a raspberry pi4b and i already installed all the Prerequisite.
In the log i get this msg: [HomebridgeADB] 
Please provide IP for this accessory: ${this.name}

I already put the ip adress of my fire tv 4k in the adb config plugin.

Thank you very much for your help.

**Comment by dwaan** [comment]
Hi, it looks like your config is in the wrong format, the plugins can't read your IP config. Take a look of the config that I attached here.
[config.json.txt](https://github.com/dwaan/homebridge-adb/files/6340928/config.json.txt)

**Comment by mrota83** [comment]
Working now :) Thank you very much
