### ISSUE TITLE
Fire Stick

### ISSUE THREAD

**Issue by Stef1972** [dwaan/homebridge-adb#46]
**Prerequisite**

1. Turn on your device.
2. Open any streaming or media app that you want.
3. Play any video.
4. Open ssh to your Homebridge server or open Terminal in Homebridge Config UI X.
5. Run this command: `adb -s DEVICE_IP_ADDRESS shell "dumpsys media_session"` copy paste the output to a text file called media_session.txt
6. Run this command: `adb -s DEVICE_IP_ADDRESS shell "dumpsys audio"` copy paste the output to a text file called audio.txt
7. Note: in my experience most of apps will appear in `dumpsys media_session` which is the preferable way to detect, but some apps (like Disney+, Cartoon Network) will appear in `dumpsys audio`

**Your Device**
Fire Stick 

**App Name**
Prime Video for the media session
Disney+ for audio session

**Attachment**
[audio.txt](https://github.com/dwaan/homebridge-adb/files/6389892/audio.txt)
[media_session.txt](https://github.com/dwaan/homebridge-adb/files/6389893/media_session.txt)

**Comment by dwaan** [comment]
It seems app like Disney+ currently can't be detected via two of those ADB methods in Fire TV.

**Comment by Stef1972** [comment]
> It seems app like Disney+ currently can't be detected via two of those ADB methods in Fire TV.

Actually the sensor is always inactive even if I play a video with prime video

**Comment by dwaan** [comment]
> > It seems app like Disney+ currently can't be detected via two of those ADB methods in Fire TV.
> 
> Actually the sensor is always inactive even if I play a video with prime video

I need to see audio and especially media_session output for Prime Video when play or pause to better understand the behaviors.

**Comment by Stef1972** [comment]
Here are all the logs. All of them refers to Primevideo.
[logs.zip](https://github.com/dwaan/homebridge-adb/files/6450323/logs.zip)

**Comment by Stef1972** [comment]
Hi dwaan, the sensor is now working much more better. There is still a problem I noticed: if I open the youtube app on the Firestick the sensor becomes active and it remains active even if I close the app, restart the homebridge, turn off and on the FireStick. I tried to exclude the youtube app from the sensor on the configuration but the issue is still present... 
The sensor remains active even if I play a video (and then I stop it) in an other app.
At a certain point randomly the sensor start to work again (until I open youtube again!)

the config:
{
                    "name": "Firestick ",
                    "ip": "192.168.1.207",
                    "interval": 5000,
                    "category": "TV_STREAMING_STICK",
                    "playbacksensor": true,
                    "playbacksensorexclude": "com.amazon.firetv.youtube",
                    "debug": false,
                    "backbutton": "KEYCODE_BACK",
                    "playpausebutton": "KEYCODE_MEDIA_PLAY_PAUSE",
                    "infobutton": "KEYCODE_HOME",
                    "hidenumber": true,
                    "hidehome": true,
                    "hideother": true,
                    "poweron": "KEYCODE_AWAKE",
                    "poweroff": "KEYCODE_SLEEP"
                }

Attached: Media_session and Audio both while Youtube app is playing or is paused
[logs_youtube.zip](https://github.com/dwaan/homebridge-adb/files/6533345/logs_youtube.zip)

**Comment by Stef1972** [comment]
The playback sensor don’t work with the new versions (v2 beta 1, v2 beta 2). It never become active even it the firestick is playing.

**Comment by dwaan** [comment]
Moved to issue #81
