### ISSUE TITLE
HDMI CEC does not work on power up

### ISSUE THREAD

**Issue by ArThuRacK** [dwaan/homebridge-adb#49]
**Describe the bug**
When I ask siri to turn off my Android Tv box, the Android TV turns off but also turns off the television through HDMI CEC (until then everything works as expected). But when I ask siri to turn on my android tv box, the android tv turns on but does not turn on the television.

**Expected behavior**
I would like that when I ask siri to turn on my android tv box, the android tv will also turn on the television (through HDMI CEC)

**Log output**
With Real Remote : 
   [5/17/2021, 10:03:00 PM] [HomebridgeADB] La télé - checkPower - true
   [5/17/2021, 10:03:28 PM] [HomebridgeADB] La télé - checkPower - false

With Homekit/Siri :
[5/17/2021, 10:03:34 PM] [HomebridgeADB] La télé - Awake
[5/17/2021, 10:03:35 PM] [HomebridgeADB] La télé - checkPower - true
[5/17/2021, 10:03:48 PM] [HomebridgeADB] La télé - Sleeping
[5/17/2021, 10:03:50 PM] [HomebridgeADB] La télé - checkPower - false
[5/17/2021, 10:03:57 PM] [HomebridgeADB] La télé - Sleeping

**Device (please complete the following information):**
 - Name: Freebox PoP

**Additional context**
I have verified that the HDMI CEC settings were all activated. I restarted my android tv box and my television several times, as well as Homebridge.

(I don't know much about it, sorry) But I have the impression that when I turn off my android tv box with Siri / Homekit, the box sends the information to my television to turn on too. But when I turn it on my android tv box, it doesn't sends the information.

When I turn on the android tv box with the real remote control, my television also turns on so I think it comes from the plug-in.

**Comment by dwaan** [comment]
Thank you for the report. I think I know the cause of the problem but still not sure about the solution yet.

**Comment by ArThuRacK** [comment]
Ok thanks !!

**Comment by dwaan** [comment]
I modified the script. And after that, the HDMI CEC works more consistent in my setup. You can try and let me know how it goes.

**Comment by ArThuRacK** [comment]
It worked !thanks
