### ISSUE TITLE
Volume Control and Live TV option

### ISSUE THREAD

**Issue by sanskardhanda** [dwaan/homebridge-adb#5]
how to use volume control and use cable tv?

**Comment by dwaan** [comment]
For volume, you can use Remote Controls from Control Center. Use your iOS device volume buttons to control the android volume when you’re inside the remote control screen. 

For Live TV or something similar, you can run the app and then check the homebridge log for app id. After that you need to input it manually to homebridge config.

**Comment by sanskardhanda** [comment]
Thanks it worked 👍
