### ISSUE TITLE
Use siri to go on an input

### ISSUE THREAD

**Issue by ArThuRacK** [dwaan/homebridge-adb#50]
**Is your feature request related to a problem? Please describe.**
I wish I could ask siri "Hey siri put Netflix on tv"

Besides, I put com.netflix.ninja as an input but when I select it in the Homekit app, nothing happens. However, this manipulation works with other applications such as Twitch or Prime Video.

**Additional context**
Latest iOS version
Latest Netflix, Android Tv version
Android TV model : Freebox PoP

**Comment by dwaan** [comment]
Hey. As far as I know, Siri still can’t change device input. I have LG TV that is supported by HomeKit, but can only ask Siri to turn it on/off and change the volume. 

But for your Netflix problem, I’ll look into it.

**Comment by ArThuRacK** [comment]
Ok thanks !

**Comment by dwaan** [comment]
I check the Netflix, somehow it have different behaviors than any other apps. But I'm able to open it via Home App all the time. So right now I still can't recreate your error, yet. 

But there is other way to open app using this plugins. In your config.json you can also add another option to the `inputs`, the option called `adb`. Over there you can add your own adb shell command to run any command, for example you can add `monkey -p com.netflix.ninja 1` to run the Netflix. Check the updated README.md for example.
