### ISSUE TITLE
I can't turn on my lamp when the plug-in is active

### ISSUE THREAD

**Issue by ArThuRacK** [dwaan/homebridge-adb#51]
sorry for inconvenience

**Describe the bug**

It looks like Homekit / siri paired my only lamp with the android tv. Let me explain :

I configured a lamp in my living room which is actually a smart plug Philips hue
It's the only light configured in my living room, so when I ask my Homepod mini (which is also in my living room) to turn on the light (I say "Hey siri, turn on the light"), siri directly understands that he has to turn on this smart plug because they are in the same room.
However, since I configured Homebridge-ADB, when I ask siri exactly the same sentence again, she refuses to turn on the smart plug (She says she cannot perform more than one action at the same time). And when I ask siri to TURN OFF the light (smart plug), this time she turns off the smart plug AND the android TV.

When I deactivate the plug-in, everything goes back to how it was before.

I also wanted to test removing the inputs to see if it wasn't related to that, but when I removed the inputs (From the hombridge UI and from the config directly, I tested both) and I have restarted the Homebridge server for the changes to take effect, the server start, then crash, then restart, in a loop.

**Expected behavior**
I would like when I ask siri "Hey siri, turn on / off the light", she would only turn on / off the light and not the android tv box (or nothing at all)

**Log output**
As an attachment
[Logs.docx](https://github.com/dwaan/homebridge-adb/files/6504185/Logs.docx)

(You can see that I also have a plug-in to control my Xbox but I also tested disabling Homebridge-ADB  to see if it was not related to this but it did not change anything)
**Device (please complete the following information):**
 - Name: Freebox Pop
 - Homepod mini / iPhone at latest version
 - Philips hue smart plug

**Additional context**
N/A

**Comment by dwaan** [comment]
I don't know what causing the interference yet, but I update the plugins and maybe it will helps with your problems.
