### ISSUE TITLE
Power On - wake and unlock device

### ISSUE THREAD

**Issue by benov84** [dwaan/homebridge-adb#52]
Hi,
there was one issue for me - poweron with KEYCODE_POWER keyevent, only wakes the screen, but device stays at lock screen.
I found a solution with this configuration:
`"poweron": "26 && input keyevent 82",`
It will be more approprivate to have two key codes that can be executed on power on event. it will be more clear for the user.
hope my experience helps :) !

**Comment by dwaan** [comment]
Thank you for the suggestion. Will consider implementing it. Currently in the new (still in beta), you can however put shell command, so you basically you can type your own adb command there. But your suggestion is more easier for some.

**Comment by dwaan** [comment]
multiple key events are implemented in version 2 currently in beta.
