### ISSUE TITLE
Ability to Specify Path to Credential Key Store

### ISSUE THREAD

**Issue by owine** [dwaan/homebridge-adb#55]
**Is your feature request related to a problem? Please describe.**
I run Homebridge in Docker with `/homebridge` as the only persistent volume in the container. This is how the docs say the container should be run. ADB defaults to `$HOME/.android` for credential key storage, however this is destroyed at container recreation as it is not part of a persistent volume. This means that every time the container was recreated I would have to reauthorize ADB on my clients which is not ideal.

**Describe the solution you'd like**
Allow a path to be manually specified to override the credential key store (i.e. `/homebridge/.android` for the ADB plugin to store credentials.

**Describe alternatives you've considered**
Override the home directory in the container to `/homebridge`. This seems to work and the credentials then end up in `/homebridge/.android`, but seems inelegant and could have second order impacts. The ability to override in the ADB plugin configuration would be preferable.

**Additional context**
N/A

**Comment by dwaan** [comment]
After reading about ADB for awhile, it seems like ADB doesn't have option to put credential keys in different folder manually. The only possible incase the homebridge instalation home folder is not persistent is to configure the home folder to different persistent folder.
