### ISSUE TITLE
Unable to turn TV on or Off

### ISSUE THREAD

**Issue by notorioustubze** [dwaan/homebridge-adb#59]
Hello, so my goal is to use this plugin to be able to control my tv that's connected to an amazon fire stick 4k.

I've successfully installed the prerequisites required to get my device to show in Homebridge and Home Kit. I have added my fire TV stick as a TV and can see it's status within HomeKit, I can also control the device via CC using the remote function as well as getting to the home menu using the switcher in HK. 

The problem I have is I can't get the TV to turn on or off via this plugin, I can use the amazon remote and turn the tv on and off but not via Home Kit.

I have previously had this Plugin working with this tv so I know it's capable.

Any ideas or solutions greatly appreciated.

**Comment by dwaan** [comment]
I think I change the default power on / off commands in few release behind and offer an option to use your preferred power on / off via the config. You can try changing them and see if it's working. As reference In the readme you can find this section:

> poweron, poweroff (optional): assign custom key event code for Power on/off, you can use KEYCODE_POWER or combination of KEYCODE_AWAKE/KEYCODE_SLEEP. See https://developer.android.com/reference/android/view/KeyEvent for the other key codes that might more suitable for your device.

**Comment by notorioustubze** [comment]
Hey, thank you for the response. I changed the combination to KEYCODE_AWAKE/KEYCODE_SLEEP and can confirm the fire stick now goes to sleep and wakes up however for the life of me I can't get it to power off or power on so the TV still remains on. I've gone through the android developer link you provided and have tried each combination that has power in the title and none of them seem to have the device change power state either.

**Comment by frangeris** [comment]
There is an option to send the code via CEC, but is not working `KEYCODE_TV_POWER`

[https://developer.android.com/reference/android/view/KeyEvent#KEYCODE_TV_POWER](https://developer.android.com/reference/android/view/KeyEvent#KEYCODE_TV_POWER)

**Comment by juliandsp91** [comment]
Hi! I'm trying to use the  `KEYCODE_TV_POWER` also but have the same problem, the TV is not going on or off. I'm sure it is possible because I can use the Amazon Echo tu switch on and off my TV with the firestick, but can't find the right command to do so, any solution?

**Comment by dwaan** [comment]
I’m closing this issue, since I’m unable to recreate the problem without having the device to test.

**Comment by Jack-XHP** [comment]
For my shield TV Pro only KEYCODE_WAKEUP/KEYCODE_SLEEP works correctly just an FYI.
