### ISSUE TITLE
Add the support of changing the tv signal

### ISSUE THREAD

**Issue by Pacoakm** [dwaan/homebridge-adb#60]
Hello, would you please add the support of changing the tv signal. Just like changing the HDMI signal.Now I just can open apps in homekit

**Comment by danielkit83** [comment]
Hope, we can execute below command as individual input to switch the TV channel on HomeKit 
TV Channel 1 adb -s 192.168.88.181 shell "input keyevent 8 && input keyevent 11"
TV Channel 2 adb -s 192.168.88.181 shell "input keyevent 8 && input keyevent 16”
TV Channel 3 adb -s 192.168.88.181 shell "input keyevent 8 && input keyevent 12”
TV Channel 4 adb -s 192.168.88.181 shell "input keyevent 9 && input keyevent 11"

**Comment by dwaan** [comment]
> Hope, we can execute below command as individual input to switch the TV channel on HomeKit 
> 
> TV Channel 1 adb -s 192.168.88.181 shell "input keyevent 8 && input keyevent 11"
> 
> TV Channel 2 adb -s 192.168.88.181 shell "input keyevent 8 && input keyevent 16”
> 
> TV Channel 3 adb -s 192.168.88.181 shell "input keyevent 8 && input keyevent 12”
> 
> TV Channel 4 adb -s 192.168.88.181 shell "input keyevent 9 && input keyevent 11"

Nice info. The current plug-ins support adb shell command as input, have you tried putting it over there? In theory it should work. Sadly my device doesn't have TV input, so I can't confirm if it's working or not.

**Comment by oscartang1** [comment]
Unfortunately the app ID is mandatory, so the adb shell command is always ignored. It will go with the app id before the adb shell command.

**Comment by dwaan** [comment]
Hey. Thank you for the report. To explain it a bit, the id is mandatory because the plug-in use it to identify which running app right now. Without it, the input selection in home app wouldn’t be working. 

But for the next problem, I will update it in the next release.

**Comment by oscartang1** [comment]
> Hey. Thank you for the report. To explain it a bit, the id is mandatory because the plug-in use it to identify which running app right now. Without it, the input selection in home app wouldn’t be working.
> 
> But for the next problem, I will update it in the next release.

Thanks a lot for your effort!
