### ISSUE TITLE
NVIDIA SHIELD checkPlayback - error 

### ISSUE THREAD

**Issue by alloploid** [dwaan/homebridge-adb#61]
Hi,

I configured adb to control Nvidia Shield. All is working, but I have error log, every second same entry.

29.09.2021, 23:53:03Kino domoweHomebridgeADBSHIELD - checkPlayback - error - using media_session

Could you help me to fix it?

**My config:**

            "platform": "HomebridgeADB",
            "accessories": [
                {
                    "name": "SHIELD",
                    "interval": 1000,
                    "ip": "192.168.0.7",
                    "playbacksensor": "false",
                    "playpauseobutton": "KEYCODE_MEDIA_PLAY_PAUSE",
                    "backbutton": "KEYCODE_BACK",
                    "infobutton": "KEYCODE_HOME",
                    "category": "TV_SET_TOP_BOX",
                    "hidenumber": true,
                    "hidehome": true,
                    "hideother": true,
                    "debug": "false",
                    "skipSpeaker": "true",
                    "inputs": [
                        {
                            "name": "Plex",
                            "id": "com.plexapp.android",
                            "adb": "activities.SplashActivity"
                        }
                    ],
                    "playpausebutton": "KEYCODE_MEDIA_PLAY_PAUSE",
                    "poweron": "KEYCODE_POWER",
                    "poweroff": "KEYCODE_POWER"
                }
            ]
        }

**Comment by dwaan** [comment]
The new version of the plugin have some improvement the playback detection. Any issue regarding with the playback will need to be based on the latest plugins version
