### ISSUE TITLE
Homebridge UI crashes whenever trying to edit the plugin

### ISSUE THREAD

**Issue by Jacksonbm1** [dwaan/homebridge-adb#65]
**Describe the bug**
Whenever I try to add inputs in the UI, the homebridge UI crashes. I'm not quite sure what's up. My server itself doesn't crash, just the webpage for my server.

**Expected behavior**
Open homebridge UI > Accessories > Homebridge ABP > Inputs > Type information

**Actual Behavior**
Open homebridge UI > Accessories > Homebridge ABP > Inputs > Crash

**Log output**
NA it is working fine

**Device (please complete the following information):**
 - Name: Raspberry PI 4B 8GB running on an SSD

**Additional context**

**Comment by Jacksonbm1** [comment]
Update, I was using chrome. Tried it in safari and it works, so it must be some weird interplay between chrome, UI, and/or ABP

**Comment by dwaan** [comment]
It looks like it's Homebridge UI X bugs. But I made some changes on how the plugins interact with Hombridge UI X, maybe you can try if it's working now.
