### ISSUE TITLE
CheckInput - error

### ISSUE THREAD

**Issue by halk1982** [dwaan/homebridge-adb#66]
**Describe the bug**
Plugin not able to detect the current running app. Error in Homebridge log is "CheckInput - Error". Tried also the command adb -s your-device-ip shell "dumpsys window windows | grep -E mFocusedApp" and I'm not getting any response back into terminal. Other than this, the device can be controlled normally, meaning switching apps, sleep, wakeup etc.
**Expected behavior**
Expected to work as my other two android devices. Both work fine from either the plugin or the command execution from terminal.
**Log output**
It is really only one error : CheckInput - Error
Let me know if you need something more than this.

**Device (please complete the following information):**
BMAX tablet, model MaxPad I10, Android version 10 
**Additional context**
Thank you very much for this amazing plugin Dwaan, I really appreciate your work and effort behind this.

**Comment by dwaan** [comment]
Hey, can you upload this command output "adb -s your-device-ip shell "dumpsys window windows" which app that currently displayed in your screen. Your Android device might have different log type. Most of my Android devices output have "mFocusedApp" in there log to identified current opening app. If I can find the word, I can add to the plugins.

**Comment by halk1982** [comment]
Hello Dwann, thank you for the super fast response. I just find out that this one worked just fine (check below):

pi@raspberrypi:~ $ adb -s 192.168.1.85  shell "dumpsys window windows | grep -E mSurface"
       mAnimationIsEntrance=true      mSurface=Surface(name=NavigationBar0)/@0xaf28624
       mAnimationIsEntrance=true      mSurface=Surface(name=StatusBar)/@0x4db151
      mSurface=Surface(name=com.synology.DScam/com.synology.DScam.activities.MainActivity)/@0x59c2d90
       mAnimationIsEntrance=true      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x86c464a

The command you asked me to run gives only a ">" as result (check below):

pi@raspberrypi:~ $ adb -s 192.168.1.85 shell "dumpsys window windows
> 

Does this mean that mSurface is the one in my case ?

**Comment by dwaan** [comment]
Yes, that should be enough. Just to make sure, are you running `com.synology.DScam.activities.MainActivity` app in the foreground when running that command?

**Comment by halk1982** [comment]
Exactly that was the app running! 

App id (or package name) is : 

com.Synology.DScam

Thank you so much Dwaan!!

**Comment by dwaan** [comment]
Oh, one more, can you run 1 or 2 more different apps and send the output of `adb -s your-device-ip shell "dumpsys window windows"`, just want to make sure the exact word will applied to other app or not.

**Comment by halk1982** [comment]
Sure thing, there you go.

3 different ones for Home, Settings & Chrome :

[For_Dwaan_Home.txt](https://github.com/dwaan/homebridge-adb/files/7822900/For_Dwaan_Home.txt)
[For_Dwaan_Chrome.txt](https://github.com/dwaan/homebridge-adb/files/7822902/For_Dwaan_Chrome.txt)
[For_Dwaan_Settings.txt](https://github.com/dwaan/homebridge-adb/files/7822903/For_Dwaan_Settings.txt)

**Comment by dwaan** [comment]
It seems like there is no consistent way to detect active app based on your outputs. But I found out that I can use this command to produce similar result `adb -s IP shell "dumpsys activity activities | grep ' ResumedActivity'"`. Can you confirm if this produce one like output of current active app in your device?

**Comment by halk1982** [comment]
Yes it does and works like a charm (check below with several apps open):

homebridge@raspberrypi:/var/lib/homebridge $ adb -s 192.168.1.85 shell "dumpsys activity activities | grep ' ResumedActivity'"
 ResumedActivity:ActivityRecord{acf4df9 u0 com.android.launcher3/com.android.searchlauncher.SearchLauncher t36}
  ResumedActivity: ActivityRecord{acf4df9 u0 com.android.launcher3/com.android.searchlauncher.SearchLauncher t36}
homebridge@raspberrypi:/var/lib/homebridge $ adb -s 192.168.1.85 shell "dumpsys activity activities | grep ' ResumedActivity'"
 ResumedActivity:ActivityRecord{c827c0f u0 com.synology.DScam/.activities.MainActivity t84}
  ResumedActivity: ActivityRecord{c827c0f u0 com.synology.DScam/.activities.MainActivity t84}
homebridge@raspberrypi:/var/lib/homebridge $ adb -s 192.168.1.85 shell "dumpsys activity activities | grep ' ResumedActivity'"
 ResumedActivity:ActivityRecord{1359b75 u0 com.android.chrome/com.google.android.apps.chrome.Main t85}
  ResumedActivity: ActivityRecord{1359b75 u0 com.android.chrome/com.google.android.apps.chrome.Main t85}
homebridge@raspberrypi:/var/lib/homebridge $ adb -s 192.168.1.85 shell "dumpsys activity activities | grep ' ResumedActivity'"
 ResumedActivity:ActivityRecord{a065697 u0 com.android.settings/.Settings t86}
  ResumedActivity: ActivityRecord{a065697 u0 com.android.settings/.Settings t86}

**Comment by halk1982** [comment]
Hello Dwaan, thank you for this, works great now! However, I now do not have app detection on the other 2 android devices, because of the "dumpsys activity activities | grep ' ResumedActivity'" not a valid command for these devices. Is it possible for you to add an option on every device to select the old or new app detection method ?

**Comment by dwaan** [comment]
> Hello Dwaan, thank you for this, works great now! However, I now do not have app detection on the other 2 android devices, because of the "dumpsys activity activities | grep ' ResumedActivity'" not a valid command for these devices. Is it possible for you to add an option on every device to select the old or new app detection method ?

Ah, thank you for the feedback. Let me get back with another update soon. I was wondering also yesterday if this will break other devices.

**Comment by halk1982** [comment]
Hello again Dwaan, just installed 1.4.12. Unfortunately I see no difference, still failing to detect running application on both older android devices (tried also to remove and re-add device to HomeKit) while the brand new one still works great (check below):

![Screen Shot 2022-01-11 at 01 22 38](https://user-images.githubusercontent.com/40629096/148854518-1ee7d448-8a07-40df-9184-6919ddd52a27.png)

After that, for troubleshooting purpose I rolled back to 1.4.11 and realised the opposite scenario. Older devices worked fine but now the new one was not (check below):

![Screen Shot 2022-01-11 at 01 08 24](https://user-images.githubusercontent.com/40629096/148854708-cec0e07f-45e7-4609-ab74-e6d521758cb6.png)

Is there anything I can do to support you on this ? Thank you again.

**Comment by dwaan** [comment]
Hi

> 

Thank you for the output, was still trying to figure out the best way to fix it. I released a new version, please try it again, and let me know if it's working now or not.

**Comment by halk1982** [comment]
Yes, I do confirm every device app is detected and works like a charm. Can't thank you enough Dwaan, I really appreciate your work.
