### ISSUE TITLE
ADB shell command not running

### ISSUE THREAD

**Issue by oscartang1** [dwaan/homebridge-adb#67]
Hi all,

im struggling to have my TV to run the adb shell command. 
basically my problem is, the app id is mandatory, so I have to put an app ID, however when I put an app ID, it will just run the app ID and skip my adb command underneath.

if I don’t put an app ID, it will not show the input.
![FF30A150-2BF9-4A57-AFEE-CE588BB6E106](https://user-images.githubusercontent.com/19954946/149701982-012f342e-f754-4dcb-a755-083f3292d871.jpeg)
![7A97F64C-2377-43A3-A665-1D9963FDD712](https://user-images.githubusercontent.com/19954946/149701984-40d0e7c0-b767-49cf-8a22-2912a870bfd6.jpeg)

**Comment by oscartang1** [comment]
Anyone is able to help on this please?

**Comment by dwaan** [comment]
Thank you for the report. Implemented in new version, currently in beta testing.
