### ISSUE TITLE
path problem

### ISSUE THREAD

**Issue by imbyoe** [dwaan/homebridge-adb#68]
**Describe the situation**
im getting an error saying that adb isnt in path even though it is. if i use adb through the cmd, it will work and even more than that, i tried to add a javascript script to the same directory as the plugin and tried to execute an adb command through there, and it worked too... what can cause this? i feel so stupid right now haha

**Log output**
Yair - connect - disconnect - 'adb' is not recognized as an internal or external command,
operable program or batch file.

**Comment by dwaan** [comment]
Normally, it just a mixed up with the ADB that they installed in their computer and ADB that supposed to be installed in the Homebridge server. 

The easiest to check if you installed ADB in your Homebridge server is to open Terminal in Homebridge Config UI and type `adb -v`

**Comment by dwaan** [comment]
New beta version implemented path option in config.json
