### ISSUE TITLE
Need more inputs for Volume up, Down, Mute 

### ISSUE THREAD

**Issue by shivanathd** [dwaan/homebridge-adb#69]
**Is your feature request related to a problem? Please describe.**
I'd like to add / control the volume / mute through the control center or even through the accessory 
**Describe the solution you'd like**
Ability to configure more input buttons to additional key events
```
"volumeup": "KEYCODE_VOLUME_UP",
"volumedown": "KEYCODE_VOLUME_DOWN",

```
**Describe alternatives you've considered**
tried adding the keycodes but they dont seem to work 
**Additional context**

**Comment by dwaan** [comment]
Does the volume control in control center using your iPhone/iPad physical volume button doesn't work to control your device's volume? Those keycodes already build inside the plugins. Except for mute.
