### ISSUE TITLE
Does this work with Windows 10?

### ISSUE THREAD

**Issue by jremy2001** [dwaan/homebridge-adb#72]
I'm able to connect to the device via adb but when I restart is says "[HomebridgeADB] Hisense - Device disconnected? Trying to reconnect" and never tries to reconnect. I've tested the output command it shows the name of my TV but it never connects or shows in the add accessories on HomeKit. I've been working on this for months but there seems to be one step that I'm missing. Do I need to add a line in the config file for it to connect each time on restart? Please help.

**Comment by dwaan** [comment]
This should work in Windows 10. I need more information to your problem. When you said restart, are you restarting your TV or the homebridge server? 

When you're starting your homebridge, is there any output saying `Hisense is running on port 49952. Please add [Hisense] manually in Home app.`? If yes, then the way to add the TV is Home app is `Add Accessory -> Tag "More options.." -> your tv should appear on the list`.

**Comment by jremy2001** [comment]
When I restart the homebridge server, the Hisense never shows as connected.
It just says Hisense is disconnected.

**Comment by dwaan** [comment]
After you restart your homebridge server, please attached the log here, preferably the logs from [HomebridgeADB] only.

**Comment by jremy2001** [comment]
[2/23/2022, 5:23:24 PM] [HomebridgeADB] 

WARNING: Can't start ADB, make sure you already installed ADB-TOOLS in your homebridge server.
Visit https://github.com/dwaan/homebridge-adb for ADB-TOOLS instalation guide.

I guess the problem I'm running to is where to instasll adb tools and where to install the location. I have it installed on the main drive but should I extract it to the the homebridge folder.  I'm not sure how to get homebridge navigate to it's installed location.

**Comment by dwaan** [comment]
In version 2 (currently in beta) there’s “path” option in config.json, to manually tell the plug-in to look at the adb executable. Or in windows, make sure the adb folder is written in windows environment variable $PATH

**Comment by dwaan** [comment]
Found a blog that can help you with your problem https://android.gadgethacks.com/how-to/make-adb-fastboot-work-any-folder-windows-0177198/

**Comment by jremy2001** [comment]
Thanks! I followed all your steps including the last post and everything is working! Make sure you have developer options enabled and to check allow USB debugging for those running into an issue.
