### ISSUE TITLE
v1.5.2, v1.5.3 breaks Homebridge

### ISSUE THREAD

**Issue by Adrian-1994** [dwaan/homebridge-adb#74]
I’m getting this error after updating..

ReferenceError: stderr is not defined
at /us/local/lib/node modules/homebridge-adb/index.js:893:51
at
/us/local/lib/node modules/homebridge-adb/index.js:940:20
at
ChildProcess.exithandler (node:child process: 406:5)
at
ChildProcess.emit (node:events:520: 28)
at
maybeClose (node: internal/child process: 1092:16)
at
Socket.<anonymous>
(node: internal/child process:451:11)
at Socket.emit (node:events:520:28)
at
Pipe.<anonymous> (node:net: 687:12)

Not only does the plug-in not work, but Homebridge becomes non-functional on these versions. Downgrading back to v1.5.0 restores functionality.

**Comment by Aekung** [comment]
Also have the same problem. Reversing back to 1.5.2 also breaks the Homebridge as well. The best thing I could do now is to temporary disable the plugin.

Note that it's been fine up until 1.5.2. I have just decided to update it to 1.5.3 today and found that it breaks Homebridge.

**Comment by dwaan** [comment]
Thank you for the report. Still working with that bugs that wasn’t appeared when I tested it few days ago. 

Sadly I can’t unpublished version 1.5.2 and 1.5.3. I did try to unpublished 1.5.2, due to some bugs I encounter after publishing it. So it best to roll back to previous version 1.5.0 or earlier manually.

**Comment by Adrian-1994** [comment]
So far, so good! Both the plugin and Homebridge are working with the beta version you published. Thank you for the fast update!

**Comment by Aekung** [comment]
The beta works for me so far as well.

Thank you very much.
