### ISSUE TITLE
Latest version recommends Node JS 17 and above but it doesn't officially support by Homebridge. 

### ISSUE THREAD

**Issue by Aekung** [dwaan/homebridge-adb#75]
**Describe the bug**
It's not really a bug but I just want to check to make sure that everything is alright as the latest version of the plugin suggests Node JS17 to be installed but Homebridge will not officially support the odd number version of Node JS so Node JS 17 is not going to be officially supported by Homebridge. In this case, will I still be able to use all the function of this plugin if I update it to the latest version but still staying with Node JS 16.X?

Does anyone have any experience of running the latest version of the plugin with Node JS 16.X or upgrading to Node JS 17 and how does that work with homebridge? It would be nice to get to hear from experienced users before jumping in either ways.

Thank you in advance.

**Comment by dwaan** [comment]
Yes. It was a typo when updating package information. But shouldn’t be a problem.

**Comment by Aekung** [comment]
Noted.

I'm updating now. Thanks for the confirmation.
