### ISSUE TITLE
How to start apps without iOS

### ISSUE THREAD

**Issue by st0nec0ld** [dwaan/homebridge-adb#8]
Hi,

i use homebridge with homebridge-gsh and google home mini. With your plugin i can successfull start/turn off my android tv box.  I add two inputs >

```
"accessories": [
    {
        "name": "Gigabox",
        "ip": "192.168.178.127",
        "interval": 5000,
        "inputs": [
            {
            "name": "YouTube",
            "id": "com.google.android.youtube.tv"
            },
            {
            "name": "Netflix",
            "id": "com.netflix.ninja"
            }
        ]
    }
],
```
I thought now i can see the inputs at the device tab.  
![homebridge](https://user-images.githubusercontent.com/21226229/93001420-1acafc80-f52f-11ea-8085-2ad2ccbe429e.PNG)
How can i start apps with my setup?

**Comment by dwaan** [comment]
Since you’re using Homebridge Config UI X, when you’re using opening it I. desktop browser, click and hold the TV icon will display the input selection. But if you’re using mobile browser, it can only turn on or off the device when you tap and hold the TV icon.
