### ISSUE TITLE
Adb 2.0.0 beta-2  playback sensor Nvidia Shield tv not working 

### ISSUE THREAD

**Issue by mrota83** [dwaan/homebridge-adb#80]
Hi'

I used the pluggin for a while and since i updated to the most recent version 2.0.0 beta-2 the playback sensor on my nvidia shield tv 2019 doesn't trigger anymore. I revented back to the last stable version 1.5.5 and its flawless.
Also tried the 2.0.0 beta-1 same thing as beta-2.

Thank you very much

**Comment by dwaan** [comment]
Hey, Thank you for the report. Rereading the 1..5.5 version to figure out what missing.

**Comment by mrota83** [comment]
With beta-3 it works when something play.
But when nothing plays the detector remains active or sometimes take 8 sec to the sensor to disengage.

thank you

**Comment by dwaan** [comment]
It’s actually an intended behavior, but it can be configure in config.json with `playbacksensordelay`, which I forget to write in readme.md, but it’s  in Homebridge Config UI X’s plugins configuration. The default value is 10 seconds if you didn’t set the value.

**Comment by dwaan** [comment]
But. Yes, you’re correct I notice the sensor sometimes didn’t turn off. Need to check on it.

**Comment by mrota83** [comment]
Thank you

**Comment by dwaan** [comment]
Merge with issue #81
