### ISSUE TITLE
FireTV playback sensor

### ISSUE THREAD

**Issue by fearlesschicken** [dwaan/homebridge-adb#82]
Your Device
FireTV (3rd gen)

App Name
Kodi for the media session
Kodi for audio session

[audio.txt](https://github.com/dwaan/homebridge-adb/files/8644334/audio.txt)
[media_session.txt](https://github.com/dwaan/homebridge-adb/files/8644335/media_session.txt)

**Comment by dwaan** [comment]
Duplicate issues #81
