### ISSUE TITLE
WoL: Unable to Wake Up from Sleep

### ISSUE THREAD

**Issue by ahmadnazirafiq** [dwaan/homebridge-adb#83]
Hi, I just got a new Haier Android TV which supports WoL and WoW. Added the correct IP and MAC address in the plugin. I’m able to put the TV to sleep however I’m unable to wake it up at all.

I’ve tried using all sorts of key_code commands like:
• KEYCODE_AWAKE
• KEYCODE_POWER
• KEYCODE_TV_POWER

Here’s an excerpt of the plugin config:

`   "hidenumber": true,
                    "hideother": false,
                    "playbacksensor": false,
                    "debug": false,
                    "upbutton": "KEYCODE_DPAD_UP",
                    "downbutton": "KEYCODE_DPAD_DOWN",
                    "leftbutton": "KEYCODE_DPAD_LEFT",
                    "rightbutton": "KEYCODE_DPAD_RIGHT",
                    "selectbutton": "KEYCODE_ENTER",
                    "backbutton": "KEYCODE_BACK",
                    "playpausebutton": "KEYCODE_MEDIA_PLAY_PAUSE",
                    "infobutton": "KEYCODE_HOME",
                    "poweron": "KEYCODE_TV_POWER KEYCODE_POWER KEYCODE_AWAKE KEYCODE_AWAKE",
                    "poweronretry": 3,
                    "poweroff": "KEYCODE_SLEEP",
                    "volumeup": "KEYCODE_VOLUME_UP",
                    "volumedown": "KEYCODE_VOLUME_DOWN"`

However, when I use a separate plugin called Homebridge WoL (https://github.com/AlexGustafsson/homebridge-wol) with the same key-code as Homebridge ADB, I’m able to both wake and sleep the TV just fine.

Do you think its a bug? I’d prefer to just stick to a single plugin instead of relying another one just to wake the TV from sleep.

**Comment by dwaan** [comment]
I think this is a bug, will look at homebridge-wol to see how they implement their wol. Thank you for the head up.

**Comment by dwaan** [comment]
Close and merge to #84 of similar issue.
