### ISSUE TITLE
Apps detect USB Debugging

### ISSUE THREAD

**Issue by hectorluisnavas** [dwaan/homebridge-adb#95]
There are applications that detect when USB Debugging is activated and do not allow you to continue using the app.
This is the case of the DirecTV app (com.directv.dtvlatam), it shows the message "To continue using the app, disable the USB Debugging option on your device"

**Log output**
After disabling USB Debugging, the device is completely unresponsive
[HomebridgeADB] TV - 🤖 Can't open: DirecTV
[HomebridgeADB] TV - 🤖 Power Off - Failed
[HomebridgeADB] TV - 🤖 Power Off - Failed

**Device**
Chromecast with GoogleTV
OS Android TV 12

**Comment by dwaan** [comment]
You can’t use this plugins without the USB debugging turned on as ADB tool relies on it. The same with network debugging, as it use the same debugging functionality. You can try other plugin I mentioned in readme https://www.npmjs.com/package/homebridge-androidtv as it could be the suitable option for your scenario.
